/**
 * Pro Player Hall of Fame — curated data mapping real esports pros/streamers
 * to GameTan archetypes. Used on archetype detail pages to show "players like you".
 */

export interface ProPlayer {
  id: string;
  name: string;
  nameEn: string;
  game: string;
  role: "pro" | "streamer" | "creator";
  region: "cn" | "kr" | "na" | "eu" | "sea" | "global";
  archetypeId: string;
  signature: string;
  signatureEn: string;
}

export const HALL_OF_FAME: ProPlayer[] = [
  // ==================== lightning-assassin ====================
  {
    id: "uzi",
    name: "Uzi (简自豪)",
    nameEn: "Uzi",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "lightning-assassin",
    signature: "手速天花板，团战中的人形印刷机",
    signatureEn: "Mechanical ceiling — a human DPS printer in teamfights",
  },
  {
    id: "bin",
    name: "Bin (陈泽彬)",
    nameEn: "Bin",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "lightning-assassin",
    signature: "上路绝境反杀王，越塔就是日常操作",
    signatureEn: "Top lane clutch king — tower dives are just routine",
  },
  {
    id: "zmjjkk",
    name: "ZmjjKK",
    nameEn: "ZmjjKK",
    game: "PUBG",
    role: "pro",
    region: "cn",
    archetypeId: "lightning-assassin",
    signature: "亚洲第一步枪，反应速度超越人类极限",
    signatureEn: "Asia's #1 rifler — reaction speed beyond human limits",
  },
  {
    id: "tenz",
    name: "TenZ",
    nameEn: "TenZ",
    game: "Valorant",
    role: "pro",
    region: "na",
    archetypeId: "lightning-assassin",
    signature: "北美闪电手，Jett的完美化身",
    signatureEn: "NA's lightning hands — the living embodiment of Jett",
  },
  {
    id: "s1mple",
    name: "s1mple",
    nameEn: "s1mple",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "lightning-assassin",
    signature: "FPS之神，操作上限无人能及",
    signatureEn: "The FPS god — mechanical ceiling no one can reach",
  },

  // ==================== berserker ====================
  {
    id: "theshy",
    name: "TheShy (姜承録)",
    nameEn: "TheShy",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "berserker",
    signature: "上路暴君，要么极限操作carry要么极限送人头",
    signatureEn: "Top lane tyrant — either hard carries or hard ints, no in-between",
  },
  {
    id: "gala",
    name: "GALA (陈伟)",
    nameEn: "GALA",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "berserker",
    signature: "敢在决赛用卡莎冲脸的男人",
    signatureEn: "The man who Kai'Sa dives into 5 in a World Finals",
  },
  {
    id: "17shou",
    name: "17Shou (一起手)",
    nameEn: "17Shou",
    game: "PUBG",
    role: "pro",
    region: "cn",
    archetypeId: "berserker",
    signature: "落地就冲，钢枪从不犹豫",
    signatureEn: "Hot drop, rush — never hesitates to take a fight",
  },
  {
    id: "w0xic",
    name: "w0xic",
    nameEn: "w0xic",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "berserker",
    signature: "最激进的狙击手，用AWP当步枪冲",
    signatureEn: "The most aggressive AWPer — pushes with a sniper like it's a rifle",
  },
  {
    id: "yay",
    name: "yay",
    nameEn: "yay",
    game: "Valorant",
    role: "pro",
    region: "na",
    archetypeId: "berserker",
    signature: "El Diablo，用Chamber碾压一切",
    signatureEn: "El Diablo — crushed everything on Chamber",
  },

  // ==================== sharpshooter ====================
  {
    id: "jian",
    name: "JackeyLove (喻文波)",
    nameEn: "Jian",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "sharpshooter",
    signature: "精准走位的ADC大师，关键团战零失误",
    signatureEn: "ADC master with surgical positioning — flawless in clutch teamfights",
  },
  {
    id: "meiko",
    name: "Meiko (田野)",
    nameEn: "Meiko",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "sharpshooter",
    signature: "辅助位的精密仪器，每个技能都打在刀刃上",
    signatureEn: "A precision instrument from support — every ability lands exactly right",
  },
  {
    id: "dev1ce",
    name: "dev1ce",
    nameEn: "dev1ce",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "sharpshooter",
    signature: "四冠王，最稳定的狙击手没有之一",
    signatureEn: "4x Major champion — the most consistent AWPer to ever play",
  },
  {
    id: "aspas",
    name: "aspas",
    nameEn: "aspas",
    game: "Valorant",
    role: "pro",
    region: "na",
    archetypeId: "sharpshooter",
    signature: "巴西之星，爆头率高到离谱",
    signatureEn: "Brazil's star — headshot rate that defies logic",
  },
  {
    id: "niko",
    name: "NiKo",
    nameEn: "NiKo",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "sharpshooter",
    signature: "步枪之王，纯粹的射击天赋无人出其右",
    signatureEn: "King of rifles — pure aim talent unmatched by anyone",
  },

  // ==================== duelist ====================
  {
    id: "doinb",
    name: "Doinb (金泰相)",
    nameEn: "Doinb",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "duelist",
    signature: "非常规中单，用脑子打赢对手的操作怪",
    signatureEn: "Unconventional mid — outplays opponents with brains and mechanics combined",
  },
  {
    id: "knight",
    name: "Knight (卓定)",
    nameEn: "Knight",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "duelist",
    signature: "中路Solo王，线上对决从未让人失望",
    signatureEn: "Mid lane solo king — never lost a 1v1 laning phase that mattered",
  },
  {
    id: "faker",
    name: "Faker (李相赫)",
    nameEn: "Faker",
    game: "League of Legends",
    role: "pro",
    region: "kr",
    archetypeId: "duelist",
    signature: "电竞之神，速度与智慧的完美结合",
    signatureEn: "The god of esports — perfect fusion of speed and intellect",
  },
  {
    id: "cned",
    name: "cNed",
    nameEn: "cNed",
    game: "Valorant",
    role: "pro",
    region: "eu",
    archetypeId: "duelist",
    signature: "Champions MVP，Jett对决永远的王",
    signatureEn: "Champions MVP — the eternal king of Jett duels",
  },
  {
    id: "coldzera",
    name: "coldzera",
    nameEn: "coldzera",
    game: "CS2",
    role: "pro",
    region: "na",
    archetypeId: "duelist",
    signature: "HLTV双年最佳，智慧型步枪选手巅峰",
    signatureEn: "Back-to-back HLTV #1 — the peak of cerebral rifling",
  },

  // ==================== oracle ====================
  {
    id: "xiao8",
    name: "Xiao8 (张宁)",
    nameEn: "Xiao8",
    game: "Dota 2",
    role: "pro",
    region: "cn",
    archetypeId: "oracle",
    signature: "人称Director8，对局势的阅读能力无出其右",
    signatureEn: "Director8 — game-reading ability beyond any other",
  },
  {
    id: "clearlove",
    name: "明凯 (Clearlove)",
    nameEn: "Clearlove",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "oracle",
    signature: "LPL四冠打野，用视野控制全图",
    signatureEn: "4x LPL champion jungler — controlled the map through vision",
  },
  {
    id: "wei",
    name: "Wei (陈之)",
    nameEn: "Wei",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "oracle",
    signature: "顶级打野嗅觉，总能在对的时间出现在对的地方",
    signatureEn: "Top-tier jungle instincts — always at the right place at the right time",
  },
  {
    id: "fallen",
    name: "FalleN",
    nameEn: "FalleN",
    game: "CS2",
    role: "pro",
    region: "na",
    archetypeId: "oracle",
    signature: "教授，用策略让整支队伍超越个人实力总和",
    signatureEn: "The Professor — strategy makes the team greater than the sum of its parts",
  },
  {
    id: "ppd",
    name: "ppd",
    nameEn: "ppd",
    game: "Dota 2",
    role: "pro",
    region: "na",
    archetypeId: "oracle",
    signature: "TI冠军队长，BP环节就赢了一半",
    signatureEn: "TI champion captain — already half won during the draft",
  },

  // ==================== fortress ====================
  {
    id: "letme",
    name: "LetMe (严君泽)",
    nameEn: "LetMe",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "fortress",
    signature: "世界赛最稳的上单，永远不会崩",
    signatureEn: "Most stable top laner at Worlds — never crumbles under pressure",
  },
  {
    id: "crisp",
    name: "Crisp (刘名辉)",
    nameEn: "Crisp",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "fortress",
    signature: "冠军辅助，队伍的情绪稳定器",
    signatureEn: "Championship support — the team's emotional anchor",
  },
  {
    id: "xyp9x",
    name: "Xyp9x",
    nameEn: "Xyp9x",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "fortress",
    signature: "离合之神，Astralis残局胜率的保证",
    signatureEn: "The Clutch Minister — Astralis' guarantee in clutch rounds",
  },
  {
    id: "hiko",
    name: "Hiko",
    nameEn: "Hiko",
    game: "Valorant",
    role: "pro",
    region: "na",
    archetypeId: "fortress",
    signature: "北美老兵，冷静到令人发指的锚点选手",
    signatureEn: "NA veteran — inhumanly calm anchor player",
  },
  {
    id: "kuroky",
    name: "KuroKy",
    nameEn: "KuroKy",
    game: "Dota 2",
    role: "pro",
    region: "eu",
    archetypeId: "fortress",
    signature: "TI冠军，从核心转型辅助的万能战士",
    signatureEn: "TI champion — transitioned from carry to support, excelled at both",
  },

  // ==================== shadow-strategist ====================
  {
    id: "rookie",
    name: "Rookie (宋义进)",
    nameEn: "Rookie",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "shadow-strategist",
    signature: "最强赛区的最强中单，用节奏碾压一切",
    signatureEn: "The strongest mid in the strongest region — tempo-crushing everyone",
  },
  {
    id: "kanavi",
    name: "Kanavi (徐镇赫)",
    nameEn: "Kanavi",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "shadow-strategist",
    signature: "Carry型打野的模板，暗处操控全局",
    signatureEn: "Template carry jungler — puppeteering the game from the shadows",
  },
  {
    id: "cadian",
    name: "cadiaN",
    nameEn: "cadiaN",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "shadow-strategist",
    signature: "指挥型狙击手，用读心术拆解对手战术",
    signatureEn: "IGL AWPer — dismantles enemy tactics with mind-reading",
  },
  {
    id: "fns",
    name: "FNS",
    nameEn: "FNS",
    game: "Valorant",
    role: "pro",
    region: "na",
    archetypeId: "shadow-strategist",
    signature: "LOUDest brain，冠军背后的战术大师",
    signatureEn: "The LOUDest brain — tactical mastermind behind the championship",
  },
  {
    id: "ame",
    name: "Ame (王淳煜)",
    nameEn: "Ame",
    game: "Dota 2",
    role: "pro",
    region: "cn",
    archetypeId: "shadow-strategist",
    signature: "TI冠军核心，沉默中碾碎对手的经济",
    signatureEn: "TI champion carry — silently crushing opponents' economy",
  },

  // ==================== gambler ====================
  {
    id: "jackeylove",
    name: "JackeyLove (喻文波)",
    nameEn: "JackeyLove",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "gambler",
    signature: "要么秀翻全场，要么闪现送人头——永远在赌",
    signatureEn: "Either hard carries or flash-ints — always gambling",
  },
  {
    id: "iboy",
    name: "iBoy (胡显昭)",
    nameEn: "iBoy",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "gambler",
    signature: "天才少年ADC，敢在世界赛脸探草丛",
    signatureEn: "Prodigy ADC — bold enough to face-check at Worlds",
  },
  {
    id: "stewie2k",
    name: "stewie2k",
    nameEn: "stewie2k",
    game: "CS2",
    role: "pro",
    region: "na",
    archetypeId: "gambler",
    signature: "烟雾弹冲脸流的发明者，对手永远猜不到他下一步",
    signatureEn: "Invented the smoke push — opponents never know what's coming next",
  },
  {
    id: "sumail",
    name: "SumaiL (苏马伊尔)",
    nameEn: "SumaiL",
    game: "Dota 2",
    role: "pro",
    region: "na",
    archetypeId: "gambler",
    signature: "16岁TI冠军，大胆到疯狂的中路风格",
    signatureEn: "TI champion at 16 — a mid lane style so bold it borders on madness",
  },
  {
    id: "electronic",
    name: "electronic",
    nameEn: "electronic",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "gambler",
    signature: "爆发力拉满的entry选手，开局就梭哈",
    signatureEn: "Explosive entry fragger — goes all-in from the opening round",
  },

  // ==================== rhythm-walker ====================
  {
    id: "angel-cn",
    name: "Angel (王兆辉)",
    nameEn: "Angel",
    game: "Valorant",
    role: "pro",
    region: "cn",
    archetypeId: "rhythm-walker",
    signature: "中国Valorant节奏大师，用tempo带动全队",
    signatureEn: "China's Valorant tempo master — drives the whole team's rhythm",
  },
  {
    id: "tokaku",
    name: "Tokaku",
    nameEn: "Tokaku",
    game: "osu!",
    role: "pro",
    region: "global",
    archetypeId: "rhythm-walker",
    signature: "手指与节拍合一，音游界的活传说",
    signatureEn: "Fingers and beats as one — a living legend of rhythm gaming",
  },
  {
    id: "rrtyui",
    name: "rrtyui",
    nameEn: "rrtyui",
    game: "osu!",
    role: "pro",
    region: "global",
    archetypeId: "rhythm-walker",
    signature: "osu!传奇，退役后依然被封神的存在",
    signatureEn: "osu! legend — still deified long after retirement",
  },
  {
    id: "chovy",
    name: "Chovy (郑知灿)",
    nameEn: "Chovy",
    game: "League of Legends",
    role: "pro",
    region: "kr",
    archetypeId: "rhythm-walker",
    signature: "补刀之神，线上节奏无可匹敌",
    signatureEn: "The CS god — laning rhythm that's utterly unmatched",
  },
  {
    id: "mrekk",
    name: "mrekk",
    nameEn: "mrekk",
    game: "osu!",
    role: "pro",
    region: "global",
    archetypeId: "rhythm-walker",
    signature: "当代osu!最强，节奏感写进DNA",
    signatureEn: "The current osu! GOAT — rhythm encoded in his DNA",
  },

  // ==================== commander ====================
  {
    id: "ming",
    name: "Ming (史森明)",
    nameEn: "Ming",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "commander",
    signature: "RNG灵魂，辅助位的团队指挥艺术家",
    signatureEn: "RNG's soul — an artist of shotcalling from the support role",
  },
  {
    id: "xiaohu",
    name: "Xiaohu (李元浩)",
    nameEn: "Xiaohu",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "commander",
    signature: "中上双修的传奇，关键团战永远做出正确选择",
    signatureEn: "Legendary mid/top flex — always makes the right call in crucial teamfights",
  },
  {
    id: "gla1ve",
    name: "gla1ve",
    nameEn: "gla1ve",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "commander",
    signature: "Astralis时代的大脑，史上最成功的指挥官",
    signatureEn: "The brain of the Astralis era — the most successful IGL in history",
  },
  {
    id: "puppey",
    name: "Puppey",
    nameEn: "Puppey",
    game: "Dota 2",
    role: "pro",
    region: "eu",
    archetypeId: "commander",
    signature: "活化石级队长，从Dota1到Dota2统治了整个时代",
    signatureEn: "Eternal captain — dominated from Dota 1 through Dota 2",
  },
  {
    id: "fly",
    name: "Fly",
    nameEn: "Fly",
    game: "Dota 2",
    role: "pro",
    region: "eu",
    archetypeId: "commander",
    signature: "OG创始人，用指挥弥补一切短板",
    signatureEn: "OG co-founder — shotcalling compensates for everything",
  },

  // ==================== weaver (conductor/multitasking) ====================
  {
    id: "sofm",
    name: "SofM (邓恒龙)",
    nameEn: "SofM",
    game: "League of Legends",
    role: "pro",
    region: "sea",
    archetypeId: "weaver",
    signature: "越南野王，多线入侵的艺术家",
    signatureEn: "Vietnam's jungle king — an artist of multi-lane invasion",
  },
  {
    id: "tian",
    name: "Tian (高天亮)",
    nameEn: "Tian",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "weaver",
    signature: "S9世界冠军FMVP，多线联动的教科书",
    signatureEn: "S9 Worlds FMVP — textbook multi-lane coordination",
  },
  {
    id: "cr1t",
    name: "Cr1t",
    nameEn: "Cr1t",
    game: "Dota 2",
    role: "pro",
    region: "eu",
    archetypeId: "weaver",
    signature: "多线拉扯辅助大师，同时影响三条线",
    signatureEn: "Multi-front support master — influencing all three lanes simultaneously",
  },
  {
    id: "brokenblade",
    name: "BrokenBlade",
    nameEn: "BrokenBlade",
    game: "League of Legends",
    role: "pro",
    region: "eu",
    archetypeId: "weaver",
    signature: "G2核心上单，同时处理线权和团战两件事",
    signatureEn: "G2's core top — manages laning and teamfight duties simultaneously",
  },
  {
    id: "canyon",
    name: "Canyon (金建步)",
    nameEn: "Canyon",
    game: "League of Legends",
    role: "pro",
    region: "kr",
    archetypeId: "weaver",
    signature: "T1打野，空间感和多线意识都是顶级",
    signatureEn: "DK jungler — top-tier spatial sense and multi-lane awareness",
  },

  // ==================== sentinel ====================
  {
    id: "369",
    name: "369 (白家浩)",
    nameEn: "369",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "sentinel",
    signature: "世界赛最稳固的前线，永远站在最正确的位置",
    signatureEn: "The most solid frontline at Worlds — always in the perfect position",
  },
  {
    id: "magisk",
    name: "Magisk",
    nameEn: "Magisk",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "sentinel",
    signature: "Astralis铁壁，站位精确到像素级别",
    signatureEn: "Astralis iron wall — positioning accurate to the pixel",
  },
  {
    id: "styko",
    name: "STYKO",
    nameEn: "STYKO",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "sentinel",
    signature: "最被低估的辅助选手，团队防守的无名英雄",
    signatureEn: "The most underrated support player — unsung hero of team defense",
  },
  {
    id: "keria",
    name: "Keria (柳民锡)",
    nameEn: "Keria",
    game: "League of Legends",
    role: "pro",
    region: "kr",
    archetypeId: "sentinel",
    signature: "T1辅助天才，用站位和视野保护整支队伍",
    signatureEn: "T1's support prodigy — protects the entire team through positioning and vision",
  },
  {
    id: "suygetsu",
    name: "Suygetsu",
    nameEn: "Suygetsu",
    game: "Valorant",
    role: "pro",
    region: "eu",
    archetypeId: "sentinel",
    signature: "NAVI防线核心，永远在最刁钻的角度等你",
    signatureEn: "NAVI's defensive core — always holding the trickiest angle",
  },

  // ==================== shapeshifter ====================
  {
    id: "scout",
    name: "Scout (李汭燦)",
    nameEn: "Scout",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "shapeshifter",
    signature: "冠军中单，任何英雄池都能拿出顶级表现",
    signatureEn: "World champion mid — delivers top-tier performances on any champion",
  },
  {
    id: "breathe",
    name: "Breathe (陈龙)",
    nameEn: "Breathe",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "shapeshifter",
    signature: "万能上单，从坦克到刺客全能驾驭",
    signatureEn: "Versatile top — excels on everything from tanks to assassins",
  },
  {
    id: "ropz",
    name: "ropz",
    nameEn: "ropz",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "shapeshifter",
    signature: "FaZe万金油，哪个位置都能打出MVP水准",
    signatureEn: "FaZe's utility player — MVP-level performance in any position",
  },
  {
    id: "derke",
    name: "Derke",
    nameEn: "Derke",
    game: "Valorant",
    role: "pro",
    region: "eu",
    archetypeId: "shapeshifter",
    signature: "Fnatic核心，角色切换毫无缝隙",
    signatureEn: "Fnatic's core — seamless role-swapping with zero drop-off",
  },
  {
    id: "showmaker",
    name: "ShowMaker (许秀)",
    nameEn: "ShowMaker",
    game: "League of Legends",
    role: "pro",
    region: "kr",
    archetypeId: "shapeshifter",
    signature: "DK中路，任何版本都能找到最强打法",
    signatureEn: "DK's mid lane — finds the optimal playstyle in every meta",
  },

  // ==================== collector (sage) ====================
  {
    id: "karsa",
    name: "Karsa (洪浩轩)",
    nameEn: "Karsa",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "collector",
    signature: "跨赛区老将，对每个版本的理解深入骨髓",
    signatureEn: "Cross-region veteran — understands every meta down to the bone",
  },
  {
    id: "pdd",
    name: "PDD (刘谋)",
    nameEn: "PDD",
    game: "League of Legends",
    role: "streamer",
    region: "cn",
    archetypeId: "collector",
    signature: "IG传奇，退役后依然是LPL活字典",
    signatureEn: "IG legend — still a walking LPL encyclopedia after retirement",
  },
  {
    id: "karrigan",
    name: "karrigan",
    nameEn: "karrigan",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "collector",
    signature: "比赛经验最丰富的IGL，记住了每张地图的每个细节",
    signatureEn: "The most experienced IGL — memorized every detail of every map",
  },
  {
    id: "n0tail",
    name: "N0tail",
    nameEn: "N0tail",
    game: "Dota 2",
    role: "pro",
    region: "eu",
    archetypeId: "collector",
    signature: "两届TI冠军，经验和记忆就是他的武器",
    signatureEn: "2x TI champion — experience and memory are his weapons",
  },
  {
    id: "missharvey",
    name: "missharvey",
    nameEn: "missharvey",
    game: "CS2",
    role: "pro",
    region: "na",
    archetypeId: "collector",
    signature: "女子CS传奇，对比赛数据的记忆力惊人",
    signatureEn: "Women's CS legend — astonishing memory for match data",
  },

  // ==================== chaos-child (survivor/creative) ====================
  {
    id: "weixiao",
    name: "WeiXiao (高学成)",
    nameEn: "WeiXiao",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "chaos-child",
    signature: "S2传奇ADC，用创造力定义了一个时代",
    signatureEn: "S2 legendary ADC — defined an era through sheer creativity",
  },
  {
    id: "xiye",
    name: "Xiye (苏汉伟)",
    nameEn: "Xiye",
    game: "League of Legends",
    role: "pro",
    region: "cn",
    archetypeId: "chaos-child",
    signature: "中单万花筒，总能掏出对手意想不到的英雄",
    signatureEn: "Kaleidoscope mid — always pulls out champions nobody expects",
  },
  {
    id: "kennys",
    name: "kennyS",
    nameEn: "kennyS",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "chaos-child",
    signature: "最华丽的狙击手，创造了一个只属于自己的时代",
    signatureEn: "The most stylish AWPer — created an era that belonged only to him",
  },
  {
    id: "olofmeister",
    name: "olofmeister",
    nameEn: "olofmeister",
    game: "CS2",
    role: "pro",
    region: "eu",
    archetypeId: "chaos-child",
    signature: "Overpass天台，CS史上最具创意的一跳",
    signatureEn: "The Overpass boost — the most creative play in CS history",
  },
  {
    id: "ana",
    name: "ana (安澜)",
    nameEn: "ana",
    game: "Dota 2",
    role: "pro",
    region: "global",
    archetypeId: "chaos-child",
    signature: "两届TI冠军核心，从退役到夺冠的传奇剧本",
    signatureEn: "2x TI champion carry — a legendary script of retirement and redemption",
  },

  // ==================== lone-wolf (extra, not in original spec but exists) ====================
  {
    id: "shroud",
    name: "shroud",
    nameEn: "shroud",
    game: "Valorant",
    role: "streamer",
    region: "na",
    archetypeId: "lone-wolf",
    signature: "退役后在每款FPS都是大神，一个人就是一支队伍",
    signatureEn: "God-tier at every FPS after retirement — a one-man army",
  },
  {
    id: "scream",
    name: "ScreaM",
    nameEn: "ScreaM",
    game: "Valorant",
    role: "pro",
    region: "eu",
    archetypeId: "lone-wolf",
    signature: "爆头机器，不需要队友配合也能1v5",
    signatureEn: "Headshot machine — doesn't need teammates to ace",
  },
  {
    id: "miracle",
    name: "Miracle- (安凯尔)",
    nameEn: "Miracle-",
    game: "Dota 2",
    role: "pro",
    region: "eu",
    archetypeId: "lone-wolf",
    signature: "9000分先生，一个人把MMR打到没有对手",
    signatureEn: "Mr. 9000 MMR — reached a rating where no one could match him",
  },
  {
    id: "jinglingwei",
    name: "精灵微 (Genshin)",
    nameEn: "JingLingWei",
    game: "Genshin Impact",
    role: "streamer",
    region: "cn",
    archetypeId: "lone-wolf",
    signature: "单人通关深渊满星，不需要五星角色",
    signatureEn: "Solo full-stars Abyss without 5-star characters",
  },
  {
    id: "wangduoyu",
    name: "王多鱼",
    nameEn: "WangDuoYu",
    game: "League of Legends",
    role: "streamer",
    region: "cn",
    archetypeId: "lone-wolf",
    signature: "国服单排之王，只靠自己上分",
    signatureEn: "CN solo queue king — climbs ranks on his own",
  },
];

// ==================== HELPER FUNCTIONS ====================

/**
 * Get pro players matching a given archetype, optionally filtered by region.
 * Region filter: "cn" returns CN players; any other value returns non-CN players (global view).
 */
export function getPlayersForArchetype(
  archetypeId: string,
  region?: string
): ProPlayer[] {
  return HALL_OF_FAME.filter((p) => {
    if (p.archetypeId !== archetypeId) return false;
    if (!region) return true;
    if (region === "cn") return p.region === "cn";
    // "global" shows everyone except CN-only
    return p.region !== "cn";
  });
}

/**
 * Get all pro players from a specific region.
 */
export function getPlayersByRegion(region: string): ProPlayer[] {
  if (region === "cn") return HALL_OF_FAME.filter((p) => p.region === "cn");
  return HALL_OF_FAME.filter((p) => p.region !== "cn");
}
