/**
 * Seed data for the games catalog.
 *
 * Genre keys must match GENRE_TALENT_MAP in constants.ts:
 *   fps | moba | rpg | rhythm | puzzle | strategy | battle_royale | racing | simulation | card
 *
 * Platform keys:
 *   pc | mobile | console | cross_platform
 *
 * To add games: append to SEED_GAMES following the SeedGame shape.
 * Then call POST /api/admin/seed to upsert into the DB.
 */

export interface SeedGame {
  name: string;
  nameEn: string;
  slug: string;
  description: string;
  descriptionEn?: string;
  developer?: string;
  publisher?: string;
  platforms: string[];
  genres: string[];
  rating: number;
  popularity: number; // 0-100, higher = more popular
  priceInfo: string;
  releaseDate?: string; // "2024-03-15" or "2024"
  coverUrl?: string;
}

// Helper: generate a slug from English name
function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

/**
 * ~120 curated popular games across all platforms and genres.
 * Organized by primary platform for readability.
 *
 * coverUrl is auto-computed from slug → /covers/{slug}.webp
 */
const _RAW_GAMES: Omit<SeedGame, "coverUrl">[] = [
  // ===== PC 端游 =====
  {
    name: "反恐精英2",
    nameEn: "Counter-Strike 2",
    slug: slugify("Counter-Strike 2"),
    description: "Valve出品的经典团队竞技射击游戏，CS系列最新作",
    platforms: ["pc"],
    genres: ["fps"],
    rating: 8.5,
    popularity: 95,
    priceInfo: "免费",
  },
  {
    name: "无畏契约",
    nameEn: "Valorant",
    slug: slugify("Valorant"),
    description: "拳头出品的5v5战术射击游戏，融合英雄技能与精准射击",
    platforms: ["pc"],
    genres: ["fps"],
    rating: 8.3,
    popularity: 90,
    priceInfo: "免费",
  },
  {
    name: "Dota 2",
    nameEn: "Dota 2",
    slug: slugify("Dota 2"),
    description: "Valve出品的经典MOBA游戏，高深度战术竞技",
    platforms: ["pc"],
    genres: ["moba", "strategy"],
    rating: 8.8,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "英雄联盟",
    nameEn: "League of Legends",
    slug: slugify("League of Legends"),
    description: "全球最受欢迎的MOBA游戏，拳头游戏旗舰之作",
    platforms: ["pc"],
    genres: ["moba"],
    rating: 8.5,
    popularity: 95,
    priceInfo: "免费",
  },
  {
    name: "守望先锋2",
    nameEn: "Overwatch 2",
    slug: slugify("Overwatch 2"),
    description: "暴雪出品的团队英雄射击游戏，强调团队配合",
    platforms: ["pc", "console"],
    genres: ["fps"],
    rating: 7.5,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "文明6",
    nameEn: "Civilization VI",
    slug: slugify("Civilization VI"),
    description: "经典回合制策略游戏，从远古文明走向太空时代",
    platforms: ["pc"],
    genres: ["strategy"],
    rating: 9.0,
    popularity: 80,
    priceInfo: "¥199",
  },
  {
    name: "城市：天际线",
    nameEn: "Cities: Skylines",
    slug: slugify("Cities Skylines"),
    description: "城市建设模拟游戏，规划和管理你的都市",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 8.8,
    popularity: 75,
    priceInfo: "¥128",
  },
  {
    name: "艾尔登法环",
    nameEn: "Elden Ring",
    slug: slugify("Elden Ring"),
    description: "FromSoftware与宫崎英高的开放世界动作RPG巨作",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.5,
    popularity: 90,
    priceInfo: "¥298",
  },
  {
    name: "巫师3：狂猎",
    nameEn: "The Witcher 3: Wild Hunt",
    slug: slugify("The Witcher 3 Wild Hunt"),
    description: "CDPR出品的史诗级开放世界RPG，猎魔人杰洛特的冒险",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.6,
    popularity: 90,
    priceInfo: "¥127",
  },
  {
    name: "博德之门3",
    nameEn: "Baldur's Gate 3",
    slug: slugify("Baldurs Gate 3"),
    description: "Larian出品的D&D规则CRPG，极致的角色扮演体验",
    platforms: ["pc", "console"],
    genres: ["rpg", "strategy"],
    rating: 9.7,
    popularity: 88,
    priceInfo: "¥298",
  },
  {
    name: "星际争霸2",
    nameEn: "StarCraft II",
    slug: slugify("StarCraft II"),
    description: "暴雪经典即时战略游戏，电竞RTS标杆",
    platforms: ["pc"],
    genres: ["strategy"],
    rating: 9.0,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "全面战争：三国",
    nameEn: "Total War: Three Kingdoms",
    slug: slugify("Total War Three Kingdoms"),
    description: "Creative Assembly出品的三国题材大战略游戏",
    platforms: ["pc"],
    genres: ["strategy"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥268",
  },
  {
    name: "缺氧",
    nameEn: "Oxygen Not Included",
    slug: slugify("Oxygen Not Included"),
    description: "Klei出品的太空殖民模拟经营，管理复杂的生存系统",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.1,
    popularity: 70,
    priceInfo: "¥79",
  },
  {
    name: "环世界",
    nameEn: "RimWorld",
    slug: slugify("RimWorld"),
    description: "AI驱动的殖民地管理模拟，每局都是独特的故事",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.3,
    popularity: 78,
    priceInfo: "¥108",
  },
  {
    name: "永劫无间",
    nameEn: "Naraka: Bladepoint",
    slug: slugify("Naraka Bladepoint"),
    description: "东方武侠题材动作大逃杀，近战格斗为核心",
    platforms: ["pc"],
    genres: ["battle_royale"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "彩虹六号：围攻",
    nameEn: "Rainbow Six Siege",
    slug: slugify("Rainbow Six Siege"),
    description: "育碧出品的战术团队射击游戏，主打环境破坏",
    platforms: ["pc", "console"],
    genres: ["fps", "strategy"],
    rating: 8.2,
    popularity: 78,
    priceInfo: "¥88",
  },
  {
    name: "绝地求生",
    nameEn: "PUBG: Battlegrounds",
    slug: slugify("PUBG Battlegrounds"),
    description: "开创大逃杀品类的里程碑射击游戏",
    platforms: ["pc"],
    genres: ["fps", "battle_royale"],
    rating: 7.5,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "命运2",
    nameEn: "Destiny 2",
    slug: slugify("Destiny 2"),
    description: "Bungie出品的科幻射击MMORPG，PvE与PvP结合",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 8.0,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "暗黑破坏神4",
    nameEn: "Diablo IV",
    slug: slugify("Diablo IV"),
    description: "暴雪经典ARPG系列最新作，暗黑风格动作角色扮演",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.0,
    popularity: 82,
    priceInfo: "¥298",
  },
  {
    name: "炉石传说",
    nameEn: "Hearthstone",
    slug: slugify("Hearthstone"),
    description: "暴雪出品的数字卡牌对战游戏，简单上手深度策略",
    platforms: ["pc", "mobile"],
    genres: ["card", "strategy"],
    rating: 8.0,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "万智牌：竞技场",
    nameEn: "Magic: The Gathering Arena",
    slug: slugify("Magic The Gathering Arena"),
    description: "经典集换式卡牌游戏的数字版，极深策略卡牌",
    platforms: ["pc", "mobile"],
    genres: ["card", "strategy"],
    rating: 8.3,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "杀戮尖塔",
    nameEn: "Slay the Spire",
    slug: slugify("Slay the Spire"),
    description: "开创Roguelike卡牌构筑品类的独立游戏神作",
    platforms: ["pc", "mobile", "console"],
    genres: ["card", "strategy"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "¥80",
  },
  {
    name: "极限竞速：地平线5",
    nameEn: "Forza Horizon 5",
    slug: slugify("Forza Horizon 5"),
    description: "微软旗舰开放世界赛车游戏，极致画面与驾驶体验",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 9.2,
    popularity: 85,
    priceInfo: "¥248",
  },
  {
    name: "尘埃拉力赛2.0",
    nameEn: "DiRT Rally 2.0",
    slug: slugify("DiRT Rally 2"),
    description: "硬核拉力赛车模拟游戏，真实越野驾驶体验",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 8.5,
    popularity: 60,
    priceInfo: "¥128",
  },
  {
    name: "戴森球计划",
    nameEn: "Dyson Sphere Program",
    slug: slugify("Dyson Sphere Program"),
    description: "国产太空工厂建设游戏，建造环绕恒星的戴森球",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.2,
    popularity: 78,
    priceInfo: "¥70",
  },
  {
    name: "工厂小镇",
    nameEn: "Factorio",
    slug: slugify("Factorio"),
    description: "极致的自动化工厂建设模拟游戏，强迫症的天堂",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.5,
    popularity: 80,
    priceInfo: "¥160",
  },
  {
    name: "黑神话：悟空",
    nameEn: "Black Myth: Wukong",
    slug: slugify("Black Myth Wukong"),
    description: "国产3A动作RPG巨作，西游题材魂like战斗",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 95,
    priceInfo: "¥268",
  },
  {
    name: "怪物猎人：荒野",
    nameEn: "Monster Hunter Wilds",
    slug: slugify("Monster Hunter Wilds"),
    description: "卡普空经典动作猎杀游戏系列，共斗巨型怪物",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.8,
    popularity: 88,
    priceInfo: "¥396",
  },

  // ===== 手机游戏 =====
  {
    name: "王者荣耀",
    nameEn: "Honor of Kings",
    slug: slugify("Honor of Kings"),
    description: "腾讯旗舰手游MOBA，国民级5v5对战游戏",
    platforms: ["mobile"],
    genres: ["moba"],
    rating: 8.5,
    popularity: 98,
    priceInfo: "免费",
  },
  {
    name: "和平精英",
    nameEn: "Game for Peace",
    slug: slugify("Game for Peace"),
    description: "腾讯出品的战术竞技手游，大逃杀玩法",
    platforms: ["mobile"],
    genres: ["fps", "battle_royale"],
    rating: 8.0,
    popularity: 92,
    priceInfo: "免费",
  },
  {
    name: "明日方舟",
    nameEn: "Arknights",
    slug: slugify("Arknights"),
    description: "鹰角出品的策略塔防手游，丰富的剧情与角色养成",
    platforms: ["mobile"],
    genres: ["strategy", "card"],
    rating: 8.8,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "蛋仔派对",
    nameEn: "Eggy Party",
    slug: slugify("Eggy Party"),
    description: "网易出品的派对竞技手游，多人闯关社交",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 7.5,
    popularity: 88,
    priceInfo: "免费",
  },
  {
    name: "节奏大师",
    nameEn: "Rhythm Master",
    slug: slugify("Rhythm Master"),
    description: "腾讯经典音乐节奏手游，多种曲目挑战",
    platforms: ["mobile"],
    genres: ["rhythm"],
    rating: 7.8,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "元梦之星",
    nameEn: "Dream Star",
    slug: slugify("Dream Star"),
    description: "腾讯出品的派对竞技游戏，创意闯关与社交",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 7.2,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "金铲铲之战",
    nameEn: "Teamfight Tactics Mobile",
    slug: slugify("Teamfight Tactics Mobile"),
    description: "拳头出品的自走棋手游，策略卡牌构筑对战",
    platforms: ["mobile"],
    genres: ["strategy", "card"],
    rating: 8.0,
    popularity: 82,
    priceInfo: "免费",
  },
  {
    name: "第五人格",
    nameEn: "Identity V",
    slug: slugify("Identity V"),
    description: "网易出品的非对称对抗手游，1v4追逃竞技",
    platforms: ["mobile"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "崩坏：星穹铁道",
    nameEn: "Honkai: Star Rail",
    slug: slugify("Honkai Star Rail"),
    description: "米哈游出品的回合制RPG，星际冒险剧情",
    platforms: ["mobile", "pc"],
    genres: ["rpg", "strategy"],
    rating: 8.8,
    popularity: 90,
    priceInfo: "免费",
  },
  {
    name: "阴阳师",
    nameEn: "Onmyoji",
    slug: slugify("Onmyoji"),
    description: "网易出品的日式和风RPG手游，式神养成对战",
    platforms: ["mobile"],
    genres: ["rpg", "card"],
    rating: 8.2,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "Phigros",
    nameEn: "Phigros",
    slug: slugify("Phigros"),
    description: "国产创新音游，动态判定线设计，优秀曲库",
    platforms: ["mobile"],
    genres: ["rhythm"],
    rating: 9.0,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "Cytus II",
    nameEn: "Cytus II",
    slug: slugify("Cytus II"),
    description: "雷亚出品的科幻故事音乐游戏，沉浸式剧情音游",
    platforms: ["mobile"],
    genres: ["rhythm"],
    rating: 9.2,
    popularity: 68,
    priceInfo: "¥18",
  },
  {
    name: "部落冲突",
    nameEn: "Clash of Clans",
    slug: slugify("Clash of Clans"),
    description: "Supercell出品的策略塔防经营游戏，全球热门",
    platforms: ["mobile"],
    genres: ["strategy", "simulation"],
    rating: 8.3,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "皇室战争",
    nameEn: "Clash Royale",
    slug: slugify("Clash Royale"),
    description: "Supercell出品的即时策略卡牌对战游戏",
    platforms: ["mobile"],
    genres: ["card", "strategy"],
    rating: 8.2,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "使命召唤手游",
    nameEn: "Call of Duty Mobile",
    slug: slugify("Call of Duty Mobile"),
    description: "动视经典FPS系列手游版，多模式射击体验",
    platforms: ["mobile"],
    genres: ["fps"],
    rating: 8.0,
    popularity: 82,
    priceInfo: "免费",
  },
  {
    name: "暗区突围",
    nameEn: "Arena Breakout",
    slug: slugify("Arena Breakout"),
    description: "腾讯出品的硬核撤离射击手游，Tarkov式玩法",
    platforms: ["mobile"],
    genres: ["fps", "strategy"],
    rating: 8.3,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "三国志·战略版",
    nameEn: "Three Kingdoms Tactics",
    slug: slugify("Three Kingdoms Tactics"),
    description: "三国题材SLG手游，大地图策略征战",
    platforms: ["mobile"],
    genres: ["strategy"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "QQ飞车手游",
    nameEn: "QQ Speed Mobile",
    slug: slugify("QQ Speed Mobile"),
    description: "腾讯经典竞速手游，休闲竞速赛车",
    platforms: ["mobile"],
    genres: ["racing"],
    rating: 7.5,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "跑跑卡丁车手游",
    nameEn: "KartRider Rush+",
    slug: slugify("KartRider Rush Plus"),
    description: "经典卡丁车竞速手游，道具与竞速双模式",
    platforms: ["mobile"],
    genres: ["racing"],
    rating: 7.8,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "开心消消乐",
    nameEn: "Happy Match",
    slug: slugify("Happy Match"),
    description: "国民级三消益智游戏，休闲解谜",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 7.0,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "最强蜗牛",
    nameEn: "Super Snail",
    slug: slugify("Super Snail"),
    description: "放置RPG手游，搞怪风格蜗牛养成冒险",
    platforms: ["mobile"],
    genres: ["rpg", "simulation"],
    rating: 7.5,
    popularity: 68,
    priceInfo: "免费",
  },
  {
    name: "绝区零",
    nameEn: "Zenless Zone Zero",
    slug: slugify("Zenless Zone Zero"),
    description: "米哈游出品的都市动作RPG手游",
    platforms: ["mobile", "pc"],
    genres: ["rpg"],
    rating: 8.2,
    popularity: 82,
    priceInfo: "免费",
  },

  // ===== 主机游戏 =====
  {
    name: "塞尔达传说：王国之泪",
    nameEn: "The Legend of Zelda: Tears of the Kingdom",
    slug: slugify("Zelda Tears of the Kingdom"),
    description: "任天堂旗舰开放世界冒险游戏，极致自由度",
    platforms: ["console"],
    genres: ["rpg", "puzzle"],
    rating: 9.7,
    popularity: 95,
    priceInfo: "¥429",
  },
  {
    name: "马里奥赛车8 豪华版",
    nameEn: "Mario Kart 8 Deluxe",
    slug: slugify("Mario Kart 8 Deluxe"),
    description: "任天堂经典竞速派对游戏，全年龄段欢乐赛车",
    platforms: ["console"],
    genres: ["racing"],
    rating: 9.2,
    popularity: 90,
    priceInfo: "¥429",
  },
  {
    name: "集合啦！动物森友会",
    nameEn: "Animal Crossing: New Horizons",
    slug: slugify("Animal Crossing New Horizons"),
    description: "任天堂治愈系生活模拟，打造你的无人岛",
    platforms: ["console"],
    genres: ["simulation"],
    rating: 9.0,
    popularity: 88,
    priceInfo: "¥429",
  },
  {
    name: "只狼：影逝二度",
    nameEn: "Sekiro: Shadows Die Twice",
    slug: slugify("Sekiro Shadows Die Twice"),
    description: "FromSoftware忍者动作游戏，弹反核心战斗系统",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.4,
    popularity: 85,
    priceInfo: "¥268",
  },
  {
    name: "宝可梦 朱/紫",
    nameEn: "Pokemon Scarlet and Violet",
    slug: slugify("Pokemon Scarlet Violet"),
    description: "宝可梦系列首个开放世界RPG，收集与对战",
    platforms: ["console"],
    genres: ["rpg"],
    rating: 7.5,
    popularity: 88,
    priceInfo: "¥429",
  },
  {
    name: "任天堂明星大乱斗 特别版",
    nameEn: "Super Smash Bros. Ultimate",
    slug: slugify("Super Smash Bros Ultimate"),
    description: "任天堂全明星格斗派对游戏，海量可玩角色",
    platforms: ["console"],
    genres: ["fps"],
    rating: 9.2,
    popularity: 85,
    priceInfo: "¥429",
  },
  {
    name: "对马岛之魂",
    nameEn: "Ghost of Tsushima",
    slug: slugify("Ghost of Tsushima"),
    description: "SIE出品的开放世界武士动作冒险游戏",
    platforms: ["console", "pc"],
    genres: ["rpg"],
    rating: 9.1,
    popularity: 82,
    priceInfo: "¥398",
  },
  {
    name: "战神：诸神黄昏",
    nameEn: "God of War Ragnarok",
    slug: slugify("God of War Ragnarok"),
    description: "圣莫妮卡出品的北欧神话动作冒险巨作",
    platforms: ["console", "pc"],
    genres: ["rpg"],
    rating: 9.4,
    popularity: 88,
    priceInfo: "¥398",
  },
  {
    name: "最终幻想16",
    nameEn: "Final Fantasy XVI",
    slug: slugify("Final Fantasy XVI"),
    description: "SE经典JRPG系列，全新动作战斗风格",
    platforms: ["console", "pc"],
    genres: ["rpg"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "¥398",
  },
  {
    name: "蔚蓝",
    nameEn: "Celeste",
    slug: slugify("Celeste"),
    description: "像素风高难度平台跳跃游戏，温暖的登山故事",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.3,
    popularity: 72,
    priceInfo: "¥70",
  },
  {
    name: "空洞骑士",
    nameEn: "Hollow Knight",
    slug: slugify("Hollow Knight"),
    description: "手绘风格银河恶魔城类游戏，庞大的地下王国",
    platforms: ["pc", "console"],
    genres: ["rpg", "puzzle"],
    rating: 9.4,
    popularity: 80,
    priceInfo: "¥48",
  },
  {
    name: "哈迪斯",
    nameEn: "Hades",
    slug: slugify("Hades"),
    description: "Supergiant出品的Roguelike动作游戏，希腊神话冥界逃脱",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.4,
    popularity: 85,
    priceInfo: "¥80",
  },
  {
    name: "星露谷物语",
    nameEn: "Stardew Valley",
    slug: slugify("Stardew Valley"),
    description: "像素风农场模拟经营游戏，治愈系种田生活",
    platforms: ["pc", "console", "mobile"],
    genres: ["simulation"],
    rating: 9.3,
    popularity: 85,
    priceInfo: "¥48",
  },
  {
    name: "超级马里奥兄弟 惊奇",
    nameEn: "Super Mario Bros. Wonder",
    slug: slugify("Super Mario Bros Wonder"),
    description: "任天堂经典2D平台游戏新作，创意惊奇花机制",
    platforms: ["console"],
    genres: ["puzzle"],
    rating: 9.0,
    popularity: 82,
    priceInfo: "¥429",
  },
  {
    name: "八方旅人2",
    nameEn: "Octopath Traveler II",
    slug: slugify("Octopath Traveler II"),
    description: "SE复古像素JRPG，八位旅人的交织命运",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.8,
    popularity: 72,
    priceInfo: "¥398",
  },

  // ===== 跨平台游戏 =====
  {
    name: "原神",
    nameEn: "Genshin Impact",
    slug: slugify("Genshin Impact"),
    description: "米哈游出品的开放世界冒险RPG，元素反应战斗系统",
    platforms: ["pc", "mobile", "console"],
    genres: ["rpg"],
    rating: 8.5,
    popularity: 95,
    priceInfo: "免费",
  },
  {
    name: "Apex英雄",
    nameEn: "Apex Legends",
    slug: slugify("Apex Legends"),
    description: "EA出品的英雄大逃杀射击游戏，快节奏战斗",
    platforms: ["pc", "console", "mobile"],
    genres: ["fps", "battle_royale"],
    rating: 8.5,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "堡垒之夜",
    nameEn: "Fortnite",
    slug: slugify("Fortnite"),
    description: "Epic出品的建造+大逃杀射击游戏，文化现象级",
    platforms: ["pc", "console", "mobile"],
    genres: ["fps", "battle_royale"],
    rating: 8.0,
    popularity: 92,
    priceInfo: "免费",
  },
  {
    name: "我的世界",
    nameEn: "Minecraft",
    slug: slugify("Minecraft"),
    description: "Mojang出品的沙盒创造游戏，无限自由建造",
    platforms: ["pc", "console", "mobile"],
    genres: ["simulation", "puzzle"],
    rating: 9.3,
    popularity: 98,
    priceInfo: "¥89",
  },
  {
    name: "火箭联盟",
    nameEn: "Rocket League",
    slug: slugify("Rocket League"),
    description: "汽车足球竞技游戏，简单规则深度玩法",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 8.8,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "糖豆人",
    nameEn: "Fall Guys",
    slug: slugify("Fall Guys"),
    description: "大型多人派对竞技游戏，可爱风闯关淘汰赛",
    platforms: ["pc", "console", "mobile"],
    genres: ["puzzle"],
    rating: 7.8,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "Among Us",
    nameEn: "Among Us",
    slug: slugify("Among Us"),
    description: "社交推理游戏，找出太空船上的冒充者",
    platforms: ["pc", "mobile", "console"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "泰拉瑞亚",
    nameEn: "Terraria",
    slug: slugify("Terraria"),
    description: "2D沙盒冒险游戏，挖掘、战斗与建造",
    platforms: ["pc", "console", "mobile"],
    genres: ["rpg", "simulation"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "¥36",
  },
  {
    name: "死亡细胞",
    nameEn: "Dead Cells",
    slug: slugify("Dead Cells"),
    description: "Roguelike银河城动作游戏，流畅战斗手感",
    platforms: ["pc", "console", "mobile"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥80",
  },
  {
    name: "饥荒联机版",
    nameEn: "Don't Starve Together",
    slug: slugify("Dont Starve Together"),
    description: "Klei出品的多人生存冒险游戏，蒂姆伯顿风格",
    platforms: ["pc", "console", "mobile"],
    genres: ["simulation", "strategy"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥24",
  },
  {
    name: "传说法师",
    nameEn: "Wizard of Legend",
    slug: slugify("Wizard of Legend"),
    description: "快节奏魔法Roguelike动作游戏",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.0,
    popularity: 60,
    priceInfo: "¥52",
  },
  {
    name: "双人成行",
    nameEn: "It Takes Two",
    slug: slugify("It Takes Two"),
    description: "Hazelight出品的双人合作冒险游戏，TGA年度最佳",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.5,
    popularity: 85,
    priceInfo: "¥198",
  },
  {
    name: "胡闹厨房2",
    nameEn: "Overcooked! 2",
    slug: slugify("Overcooked 2"),
    description: "混乱多人合作烹饪游戏，考验配合与手速",
    platforms: ["pc", "console"],
    genres: ["simulation", "puzzle"],
    rating: 8.8,
    popularity: 75,
    priceInfo: "¥100",
  },
  {
    name: "人类一败涂地",
    nameEn: "Human: Fall Flat",
    slug: slugify("Human Fall Flat"),
    description: "物理解谜冒险游戏，搞怪操作带来欢笑",
    platforms: ["pc", "console", "mobile"],
    genres: ["puzzle"],
    rating: 8.0,
    popularity: 75,
    priceInfo: "¥48",
  },
  {
    name: "无人深空",
    nameEn: "No Man's Sky",
    slug: slugify("No Mans Sky"),
    description: "Hello Games出品的太空探索生存游戏，程序生成宇宙",
    platforms: ["pc", "console"],
    genres: ["simulation", "rpg"],
    rating: 8.5,
    popularity: 75,
    priceInfo: "¥130",
  },
  {
    name: "英灵神殿",
    nameEn: "Valheim",
    slug: slugify("Valheim"),
    description: "北欧神话主题的多人生存建造游戏",
    platforms: ["pc"],
    genres: ["simulation", "rpg"],
    rating: 8.8,
    popularity: 78,
    priceInfo: "¥68",
  },
  {
    name: "恐鬼症",
    nameEn: "Phasmophobia",
    slug: slugify("Phasmophobia"),
    description: "四人合作恐怖调查游戏，调查超自然现象",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥46",
  },
  {
    name: "幻兽帕鲁",
    nameEn: "Palworld",
    slug: slugify("Palworld"),
    description: "怪物收集+生存建造游戏，帕鲁世界冒险",
    platforms: ["pc", "console"],
    genres: ["rpg", "simulation"],
    rating: 7.8,
    popularity: 88,
    priceInfo: "¥90",
  },
  {
    name: "三角战略",
    nameEn: "Triangle Strategy",
    slug: slugify("Triangle Strategy"),
    description: "SE出品的像素风战棋RPG，多路线分支剧情",
    platforms: ["pc", "console"],
    genres: ["strategy", "rpg"],
    rating: 8.5,
    popularity: 65,
    priceInfo: "¥398",
  },
  {
    name: "火焰纹章：风花雪月",
    nameEn: "Fire Emblem: Three Houses",
    slug: slugify("Fire Emblem Three Houses"),
    description: "任天堂经典战棋RPG，三学级剧情路线",
    platforms: ["console"],
    genres: ["strategy", "rpg"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥429",
  },
  {
    name: "勇者斗恶龙11",
    nameEn: "Dragon Quest XI",
    slug: slugify("Dragon Quest XI"),
    description: "SE经典日式RPG系列，传统JRPG的集大成之作",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 75,
    priceInfo: "¥298",
  },
  {
    name: "女神异闻录5 皇家版",
    nameEn: "Persona 5 Royal",
    slug: slugify("Persona 5 Royal"),
    description: "ATLUS经典JRPG，日常校园+异界战斗",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.5,
    popularity: 82,
    priceInfo: "¥398",
  },
  {
    name: "节奏光剑",
    nameEn: "Beat Saber",
    slug: slugify("Beat Saber"),
    description: "VR音乐节奏游戏，光剑切割音符，极致沉浸",
    platforms: ["pc"],
    genres: ["rhythm"],
    rating: 9.2,
    popularity: 78,
    priceInfo: "¥99",
  },
  {
    name: "太鼓达人",
    nameEn: "Taiko no Tatsujin",
    slug: slugify("Taiko no Tatsujin"),
    description: "万代经典太鼓音乐节奏游戏，咚咚咔咔！",
    platforms: ["console", "mobile"],
    genres: ["rhythm"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥300",
  },
  {
    name: "DEEMO",
    nameEn: "DEEMO",
    slug: slugify("DEEMO"),
    description: "雷亚出品的钢琴风音乐游戏，唯美故事",
    platforms: ["mobile", "console"],
    genres: ["rhythm"],
    rating: 9.0,
    popularity: 68,
    priceInfo: "¥12",
  },
  {
    name: "极品飞车：不羁",
    nameEn: "Need for Speed Unbound",
    slug: slugify("Need for Speed Unbound"),
    description: "EA旗舰赛车游戏，街头竞速文化",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 7.8,
    popularity: 72,
    priceInfo: "¥298",
  },
  {
    name: "GT赛车7",
    nameEn: "Gran Turismo 7",
    slug: slugify("Gran Turismo 7"),
    description: "索尼旗舰模拟赛车游戏，真实驾驶体验",
    platforms: ["console"],
    genres: ["racing"],
    rating: 8.8,
    popularity: 78,
    priceInfo: "¥498",
  },
  {
    name: "马里奥+疯狂兔子",
    nameEn: "Mario + Rabbids Sparks of Hope",
    slug: slugify("Mario Rabbids Sparks of Hope"),
    description: "育碧出品的马里奥回合策略游戏",
    platforms: ["console"],
    genres: ["strategy"],
    rating: 8.5,
    popularity: 68,
    priceInfo: "¥399",
  },
  {
    name: "潜水员戴夫",
    nameEn: "Dave the Diver",
    slug: slugify("Dave the Diver"),
    description: "深海探险+寿司店经营的混合独立游戏",
    platforms: ["pc", "console"],
    genres: ["simulation", "rpg"],
    rating: 9.0,
    popularity: 80,
    priceInfo: "¥138",
  },
  {
    name: "异度之刃3",
    nameEn: "Xenoblade Chronicles 3",
    slug: slugify("Xenoblade Chronicles 3"),
    description: "Monolith出品的史诗级JRPG，庞大世界观",
    platforms: ["console"],
    genres: ["rpg"],
    rating: 8.8,
    popularity: 72,
    priceInfo: "¥429",
  },
  {
    name: "生化危机4 重制版",
    nameEn: "Resident Evil 4 Remake",
    slug: slugify("Resident Evil 4 Remake"),
    description: "卡普空经典恐怖射击游戏重制版",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 9.2,
    popularity: 85,
    priceInfo: "¥325",
  },
  {
    name: "植物大战僵尸2",
    nameEn: "Plants vs. Zombies 2",
    slug: slugify("Plants vs Zombies 2"),
    description: "经典策略塔防游戏续作，植物守卫家园",
    platforms: ["mobile"],
    genres: ["strategy", "puzzle"],
    rating: 7.5,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "荒野乱斗",
    nameEn: "Brawl Stars",
    slug: slugify("Brawl Stars"),
    description: "Supercell出品的多人竞技手游，多种对战模式",
    platforms: ["mobile"],
    genres: ["fps", "moba"],
    rating: 8.2,
    popularity: 82,
    priceInfo: "免费",
  },
  {
    name: "文明变革2",
    nameEn: "Civilization Revolution 2",
    slug: slugify("Civilization Revolution 2"),
    description: "文明系列手机简化版，随时随地策略征服",
    platforms: ["mobile"],
    genres: ["strategy"],
    rating: 7.5,
    popularity: 55,
    priceInfo: "¥30",
  },
  {
    name: "纪念碑谷",
    nameEn: "Monument Valley",
    slug: slugify("Monument Valley"),
    description: "ustwo出品的视觉错觉解谜游戏，极简美学",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "¥25",
  },
  {
    name: "密室逃脱",
    nameEn: "The Room",
    slug: slugify("The Room"),
    description: "Fireproof出品的3D机关解谜游戏系列",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 9.0,
    popularity: 72,
    priceInfo: "¥6",
  },
  {
    name: "旷野之息",
    nameEn: "The Legend of Zelda: Breath of the Wild",
    slug: slugify("Zelda Breath of the Wild"),
    description: "任天堂重新定义开放世界的杰作，自由探索海拉鲁",
    platforms: ["console"],
    genres: ["rpg", "puzzle"],
    rating: 9.8,
    popularity: 95,
    priceInfo: "¥429",
  },
  {
    name: "喷射战士3",
    nameEn: "Splatoon 3",
    slug: slugify("Splatoon 3"),
    description: "任天堂出品的涂色射击对战游戏",
    platforms: ["console"],
    genres: ["fps"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "¥429",
  },
  {
    name: "斯普拉遁3",
    nameEn: "Pikmin 4",
    slug: slugify("Pikmin 4"),
    description: "任天堂出品的策略冒险游戏，指挥小精灵皮克敏",
    platforms: ["console"],
    genres: ["strategy", "puzzle"],
    rating: 8.8,
    popularity: 70,
    priceInfo: "¥429",
  },
  {
    name: "以撒的结合",
    nameEn: "The Binding of Isaac",
    slug: slugify("The Binding of Isaac"),
    description: "经典Roguelike地牢射击游戏，海量道具组合",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 75,
    priceInfo: "¥48",
  },
  {
    name: "深岩银河",
    nameEn: "Deep Rock Galactic",
    slug: slugify("Deep Rock Galactic"),
    description: "四人合作矿洞射击游戏，太空矮人挖矿打虫",
    platforms: ["pc", "console"],
    genres: ["fps"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥68",
  },
  {
    name: "逃脱者2",
    nameEn: "The Escapists 2",
    slug: slugify("The Escapists 2"),
    description: "像素风越狱模拟游戏，策略规划逃脱方案",
    platforms: ["pc", "console", "mobile"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 65,
    priceInfo: "¥68",
  },
  {
    name: "模拟城市：建设",
    nameEn: "SimCity BuildIt",
    slug: slugify("SimCity BuildIt"),
    description: "EA经典城市建设模拟手游",
    platforms: ["mobile"],
    genres: ["simulation"],
    rating: 7.5,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "影之诗",
    nameEn: "Shadowverse",
    slug: slugify("Shadowverse"),
    description: "Cygames出品的日系动漫风卡牌对战游戏",
    platforms: ["pc", "mobile"],
    genres: ["card"],
    rating: 8.0,
    popularity: 65,
    priceInfo: "免费",
  },
  {
    name: "游戏王：大师决斗",
    nameEn: "Yu-Gi-Oh! Master Duel",
    slug: slugify("Yu-Gi-Oh Master Duel"),
    description: "KONAMI出品的游戏王数字卡牌对战游戏",
    platforms: ["pc", "console", "mobile"],
    genres: ["card", "strategy"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "漫威终极逆转",
    nameEn: "Marvel Snap",
    slug: slugify("Marvel Snap"),
    description: "漫威IP快节奏策略卡牌游戏，每局3分钟",
    platforms: ["pc", "mobile"],
    genres: ["card"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "传送门2",
    nameEn: "Portal 2",
    slug: slugify("Portal 2"),
    description: "Valve出品的第一人称物理解谜游戏，神级关卡设计",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.6,
    popularity: 82,
    priceInfo: "¥36",
  },
  {
    name: "见证者",
    nameEn: "The Witness",
    slug: slugify("The Witness"),
    description: "Jonathan Blow出品的开放世界解谜游戏，线条谜题",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.0,
    popularity: 65,
    priceInfo: "¥138",
  },
  {
    name: "超级马里奥：奥德赛",
    nameEn: "Super Mario Odyssey",
    slug: slugify("Super Mario Odyssey"),
    description: "任天堂3D平台动作冒险游戏，帽子附身机制",
    platforms: ["console"],
    genres: ["puzzle"],
    rating: 9.5,
    popularity: 88,
    priceInfo: "¥429",
  },
  {
    name: "地铁：离去",
    nameEn: "Metro Exodus",
    slug: slugify("Metro Exodus"),
    description: "4A Games出品的末世FPS冒险游戏，俄罗斯废土",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥198",
  },
  {
    name: "流放之路",
    nameEn: "Path of Exile",
    slug: slugify("Path of Exile"),
    description: "GGG出品的免费ARPG，极致暗黑风格与Build深度",
    platforms: ["pc"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "赛博朋克2077",
    nameEn: "Cyberpunk 2077",
    slug: slugify("Cyberpunk 2077"),
    description: "CDPR出品的开放世界赛博朋克RPG",
    platforms: ["pc", "console"],
    genres: ["rpg", "fps"],
    rating: 8.5,
    popularity: 88,
    priceInfo: "¥298",
  },
  {
    name: "Baba Is You",
    nameEn: "Baba Is You",
    slug: slugify("Baba Is You"),
    description: "创新规则解谜游戏，推动文字改变游戏规则",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.3,
    popularity: 70,
    priceInfo: "¥48",
  },
  {
    name: "异星工厂2",
    nameEn: "Factorio 2",
    slug: slugify("Shapez"),
    description: "抽象工厂自动化游戏，设计和优化形状处理流水线",
    platforms: ["pc"],
    genres: ["puzzle", "simulation"],
    rating: 8.8,
    popularity: 65,
    priceInfo: "¥36",
  },
  {
    name: "激战2",
    nameEn: "Guild Wars 2",
    slug: slugify("Guild Wars 2"),
    description: "ArenaNet出品的MMORPG，动态事件与WvW",
    platforms: ["pc"],
    genres: ["rpg"],
    rating: 8.5,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "最终幻想14",
    nameEn: "Final Fantasy XIV",
    slug: slugify("Final Fantasy XIV"),
    description: "SE出品的MMORPG，顶级剧情与副本设计",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "月卡制",
  },
  {
    name: "Dota自走棋",
    nameEn: "Auto Chess",
    slug: slugify("Auto Chess"),
    description: "开创自走棋品类的策略对战游戏",
    platforms: ["pc", "mobile"],
    genres: ["strategy", "card"],
    rating: 7.8,
    popularity: 65,
    priceInfo: "免费",
  },
  {
    name: "光·遇",
    nameEn: "Sky: Children of the Light",
    slug: slugify("Sky Children of the Light"),
    description: "陈星汉出品的社交冒险游戏，唯美飞翔体验",
    platforms: ["mobile", "console"],
    genres: ["puzzle", "simulation"],
    rating: 8.8,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "决战！平安京",
    nameEn: "Onmyoji Arena",
    slug: slugify("Onmyoji Arena"),
    description: "网易出品的阴阳师IP MOBA手游",
    platforms: ["mobile"],
    genres: ["moba"],
    rating: 7.8,
    popularity: 65,
    priceInfo: "免费",
  },
  {
    name: "重返未来：1999",
    nameEn: "Reverse: 1999",
    slug: slugify("Reverse 1999"),
    description: "回合制卡牌RPG手游，复古奇幻世界观",
    platforms: ["mobile", "pc"],
    genres: ["rpg", "card"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "全境封锁2",
    nameEn: "Tom Clancy's The Division 2",
    slug: slugify("The Division 2"),
    description: "育碧出品的开放世界TPS刷装备射击游戏",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 8.0,
    popularity: 70,
    priceInfo: "¥198",
  },
  {
    name: "群星",
    nameEn: "Stellaris",
    slug: slugify("Stellaris"),
    description: "P社出品的太空大战略游戏，银河帝国经营",
    platforms: ["pc", "console"],
    genres: ["strategy", "simulation"],
    rating: 8.8,
    popularity: 72,
    priceInfo: "¥112",
  },

  // ===== 桌游 =====
  {
    name: "卡坦岛",
    nameEn: "Catan",
    slug: slugify("Catan"),
    description: "经典资源交换策略桌游，开拓定居点争夺资源",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 8.8,
    popularity: 90,
    priceInfo: "",
  },
  {
    name: "卡卡颂",
    nameEn: "Carcassonne",
    slug: slugify("Carcassonne"),
    description: "经典放置类桌游，拼放地块建造中世纪法国城市",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.5,
    popularity: 82,
    priceInfo: "",
  },
  {
    name: "璀璨宝石",
    nameEn: "Splendor",
    slug: slugify("Splendor"),
    description: "文艺复兴宝石商人引擎构筑桌游，简单规则深度策略",
    platforms: ["cross_platform"],
    genres: ["strategy"],
    rating: 8.3,
    popularity: 80,
    priceInfo: "",
  },
  {
    name: "三国杀",
    nameEn: "Legends of the Three Kingdoms",
    slug: slugify("Legends of the Three Kingdoms"),
    description: "国产经典身份推理卡牌桌游，三国角色能力对决",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 8.0,
    popularity: 88,
    priceInfo: "",
  },
  {
    name: "狼人杀",
    nameEn: "Werewolf",
    slug: slugify("Werewolf"),
    description: "经典社交推理派对游戏，白天投票夜晚杀人",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 85,
    priceInfo: "",
  },
  {
    name: "UNO",
    nameEn: "UNO",
    slug: slugify("UNO"),
    description: "全球最流行的派对卡牌游戏，简单欢乐的出牌对决",
    platforms: ["cross_platform"],
    genres: ["card"],
    rating: 7.5,
    popularity: 92,
    priceInfo: "",
  },
  {
    name: "大富翁",
    nameEn: "Monopoly",
    slug: slugify("Monopoly"),
    description: "经典地产交易桌游，买卖房产成为富豪",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 7.2,
    popularity: 90,
    priceInfo: "",
  },
  {
    name: "农场主",
    nameEn: "Agricola",
    slug: slugify("Agricola"),
    description: "经典工人放置农场经营桌游，精密的资源管理挑战",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 8.5,
    popularity: 70,
    priceInfo: "",
  },
  {
    name: "七大奇迹",
    nameEn: "7 Wonders",
    slug: slugify("7 Wonders"),
    description: "文明建设卡牌轮抽桌游，建造世界奇迹",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "",
  },
  {
    name: "电力公司",
    nameEn: "Power Grid",
    slug: slugify("Power Grid"),
    description: "电力市场竞价经营桌游，拍卖+资源管理经典",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 8.6,
    popularity: 68,
    priceInfo: "",
  },
  {
    name: "瘟疫危机",
    nameEn: "Pandemic",
    slug: slugify("Pandemic"),
    description: "合作类桌游经典，共同对抗全球传染病爆发",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.5,
    popularity: 82,
    priceInfo: "",
  },
  {
    name: "暗杀神",
    nameEn: "Ascension",
    slug: slugify("Ascension"),
    description: "快节奏卡牌构筑对战桌游，击败怪物积累荣耀",
    platforms: ["cross_platform"],
    genres: ["card"],
    rating: 7.8,
    popularity: 60,
    priceInfo: "",
  },
  {
    name: "阿瓦隆",
    nameEn: "The Resistance: Avalon",
    slug: slugify("The Resistance Avalon"),
    description: "亚瑟王题材社交推理桌游，好人与间谍的信息博弈",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.3,
    popularity: 78,
    priceInfo: "",
  },
  {
    name: "矮人矿坑",
    nameEn: "Saboteur",
    slug: slugify("Saboteur"),
    description: "隐藏身份派对桌游，挖金矿还是搞破坏？",
    platforms: ["cross_platform"],
    genres: ["card", "puzzle"],
    rating: 7.5,
    popularity: 72,
    priceInfo: "",
  },
  {
    name: "花火",
    nameEn: "Hanabi",
    slug: slugify("Hanabi"),
    description: "合作推理卡牌桌游，你看不到自己的手牌",
    platforms: ["cross_platform"],
    genres: ["card", "puzzle"],
    rating: 8.0,
    popularity: 65,
    priceInfo: "",
  },
  {
    name: "情书",
    nameEn: "Love Letter",
    slug: slugify("Love Letter"),
    description: "极简推理卡牌桌游，仅16张牌的精巧博弈",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 7.8,
    popularity: 72,
    priceInfo: "",
  },
  {
    name: "富饶之城",
    nameEn: "Citadels",
    slug: slugify("Citadels"),
    description: "角色选择城市建设桌游，身份博弈与资源竞争",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 8.0,
    popularity: 68,
    priceInfo: "",
  },
  {
    name: "拉密",
    nameEn: "Rummikub",
    slug: slugify("Rummikub"),
    description: "经典数字组合桌游，摆放数字牌组成顺子和刻子",
    platforms: ["cross_platform"],
    genres: ["puzzle", "strategy"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "",
  },
  {
    name: "国际象棋",
    nameEn: "Chess",
    slug: slugify("Chess"),
    description: "人类历史上最经典的二人策略对弈游戏",
    platforms: ["cross_platform"],
    genres: ["strategy"],
    rating: 9.5,
    popularity: 95,
    priceInfo: "",
  },
  {
    name: "围棋",
    nameEn: "Go",
    slug: slugify("Go"),
    description: "东方最深邃的策略对弈游戏，黑白子间的宇宙",
    platforms: ["cross_platform"],
    genres: ["strategy"],
    rating: 9.5,
    popularity: 85,
    priceInfo: "",
  },
];

/** Exported with auto-computed coverUrl from slug */
export const SEED_GAMES: SeedGame[] = _RAW_GAMES.map((g) => ({
  ...g,
  coverUrl: `/covers/${g.slug}.webp`,
}));
