import type { RawSeedGame } from "./types";
import { slugify } from "./types";

export const BOARD_GAMES: RawSeedGame[] = [
  {
    name: "卡坦岛",
    nameEn: "Catan",
    slug: slugify("Catan"),
    description: "经典资源交换策略桌游，开拓定居点争夺资源",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 8.8,
    popularity: 90,
    priceInfo: "",
  },
  {
    name: "卡卡颂",
    nameEn: "Carcassonne",
    slug: slugify("Carcassonne"),
    description: "经典放置类桌游，拼放地块建造中世纪法国城市",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.5,
    popularity: 82,
    priceInfo: "",
  },
  {
    name: "璀璨宝石",
    nameEn: "Splendor",
    slug: slugify("Splendor"),
    description: "文艺复兴宝石商人引擎构筑桌游，简单规则深度策略",
    platforms: ["cross_platform"],
    genres: ["strategy"],
    rating: 8.3,
    popularity: 80,
    priceInfo: "",
  },
  {
    name: "三国杀",
    nameEn: "Legends of the Three Kingdoms",
    slug: slugify("Legends of the Three Kingdoms"),
    description: "国产经典身份推理卡牌桌游，三国角色能力对决",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 8.0,
    popularity: 88,
    priceInfo: "",
  },
  {
    name: "狼人杀",
    nameEn: "Werewolf",
    slug: slugify("Werewolf"),
    description: "经典社交推理派对游戏，白天投票夜晚杀人",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 85,
    priceInfo: "",
  },
  {
    name: "UNO",
    nameEn: "UNO",
    slug: slugify("UNO"),
    description: "全球最流行的派对卡牌游戏，简单欢乐的出牌对决",
    platforms: ["cross_platform"],
    genres: ["card"],
    rating: 7.5,
    popularity: 92,
    priceInfo: "",
  },
  {
    name: "大富翁",
    nameEn: "Monopoly",
    slug: slugify("Monopoly"),
    description: "经典地产交易桌游，买卖房产成为富豪",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 7.2,
    popularity: 90,
    priceInfo: "",
  },
  {
    name: "农场主",
    nameEn: "Agricola",
    slug: slugify("Agricola"),
    description: "经典工人放置农场经营桌游，精密的资源管理挑战",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 8.5,
    popularity: 70,
    priceInfo: "",
  },
  {
    name: "七大奇迹",
    nameEn: "7 Wonders",
    slug: slugify("7 Wonders"),
    description: "文明建设卡牌轮抽桌游，建造世界奇迹",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "",
  },
  {
    name: "电力公司",
    nameEn: "Power Grid",
    slug: slugify("Power Grid"),
    description: "电力市场竞价经营桌游，拍卖+资源管理经典",
    platforms: ["cross_platform"],
    genres: ["strategy", "simulation"],
    rating: 8.6,
    popularity: 68,
    priceInfo: "",
  },
  {
    name: "瘟疫危机",
    nameEn: "Pandemic",
    slug: slugify("Pandemic"),
    description: "合作类桌游经典，共同对抗全球传染病爆发",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.5,
    popularity: 82,
    priceInfo: "",
  },
  {
    name: "暗杀神",
    nameEn: "Ascension",
    slug: slugify("Ascension"),
    description: "快节奏卡牌构筑对战桌游，击败怪物积累荣耀",
    platforms: ["cross_platform"],
    genres: ["card"],
    rating: 7.8,
    popularity: 60,
    priceInfo: "",
  },
  {
    name: "阿瓦隆",
    nameEn: "The Resistance: Avalon",
    slug: slugify("The Resistance Avalon"),
    description: "亚瑟王题材社交推理桌游，好人与间谍的信息博弈",
    platforms: ["cross_platform"],
    genres: ["strategy", "puzzle"],
    rating: 8.3,
    popularity: 78,
    priceInfo: "",
  },
  {
    name: "矮人矿坑",
    nameEn: "Saboteur",
    slug: slugify("Saboteur"),
    description: "隐藏身份派对桌游，挖金矿还是搞破坏？",
    platforms: ["cross_platform"],
    genres: ["card", "puzzle"],
    rating: 7.5,
    popularity: 72,
    priceInfo: "",
  },
  {
    name: "花火",
    nameEn: "Hanabi",
    slug: slugify("Hanabi"),
    description: "合作推理卡牌桌游，你看不到自己的手牌",
    platforms: ["cross_platform"],
    genres: ["card", "puzzle"],
    rating: 8.0,
    popularity: 65,
    priceInfo: "",
  },
  {
    name: "情书",
    nameEn: "Love Letter",
    slug: slugify("Love Letter"),
    description: "极简推理卡牌桌游，仅16张牌的精巧博弈",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 7.8,
    popularity: 72,
    priceInfo: "",
  },
  {
    name: "富饶之城",
    nameEn: "Citadels",
    slug: slugify("Citadels"),
    description: "角色选择城市建设桌游，身份博弈与资源竞争",
    platforms: ["cross_platform"],
    genres: ["card", "strategy"],
    rating: 8.0,
    popularity: 68,
    priceInfo: "",
  },
  {
    name: "拉密",
    nameEn: "Rummikub",
    slug: slugify("Rummikub"),
    description: "经典数字组合桌游，摆放数字牌组成顺子和刻子",
    platforms: ["cross_platform"],
    genres: ["puzzle", "strategy"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "",
  },
  {
    name: "国际象棋",
    nameEn: "Chess",
    slug: slugify("Chess"),
    description: "人类历史上最经典的二人策略对弈游戏",
    platforms: ["cross_platform"],
    genres: ["strategy"],
    rating: 9.5,
    popularity: 95,
    priceInfo: "",
  },
  {
    name: "围棋",
    nameEn: "Go",
    slug: slugify("Go"),
    description: "东方最深邃的策略对弈游戏，黑白子间的宇宙",
    platforms: ["cross_platform"],
    genres: ["strategy"],
    rating: 9.5,
    popularity: 85,
    priceInfo: "",
  },
];
