import type { RawSeedGame } from "./types";
import { slugify } from "./types";

export const CONSOLE_GAMES: RawSeedGame[] = [
  {
    name: "塞尔达传说：王国之泪",
    nameEn: "The Legend of Zelda: Tears of the Kingdom",
    slug: slugify("Zelda Tears of the Kingdom"),
    description: "任天堂旗舰开放世界冒险游戏，极致自由度",
    platforms: ["console"],
    genres: ["rpg", "puzzle"],
    rating: 9.7,
    popularity: 95,
    priceInfo: "¥429",
  },
  {
    name: "马里奥赛车8 豪华版",
    nameEn: "Mario Kart 8 Deluxe",
    slug: slugify("Mario Kart 8 Deluxe"),
    description: "任天堂经典竞速派对游戏，全年龄段欢乐赛车",
    platforms: ["console"],
    genres: ["racing"],
    rating: 9.2,
    popularity: 90,
    priceInfo: "¥429",
  },
  {
    name: "集合啦！动物森友会",
    nameEn: "Animal Crossing: New Horizons",
    slug: slugify("Animal Crossing New Horizons"),
    description: "任天堂治愈系生活模拟，打造你的无人岛",
    platforms: ["console"],
    genres: ["simulation"],
    rating: 9.0,
    popularity: 88,
    priceInfo: "¥429",
  },
  {
    name: "只狼：影逝二度",
    nameEn: "Sekiro: Shadows Die Twice",
    slug: slugify("Sekiro Shadows Die Twice"),
    description: "FromSoftware忍者动作游戏，弹反核心战斗系统",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.4,
    popularity: 85,
    priceInfo: "¥268",
  },
  {
    name: "宝可梦 朱/紫",
    nameEn: "Pokemon Scarlet and Violet",
    slug: slugify("Pokemon Scarlet Violet"),
    description: "宝可梦系列首个开放世界RPG，收集与对战",
    platforms: ["console"],
    genres: ["rpg"],
    rating: 7.5,
    popularity: 88,
    priceInfo: "¥429",
  },
  {
    name: "任天堂明星大乱斗 特别版",
    nameEn: "Super Smash Bros. Ultimate",
    slug: slugify("Super Smash Bros Ultimate"),
    description: "任天堂全明星格斗派对游戏，海量可玩角色",
    platforms: ["console"],
    genres: ["fps"],
    rating: 9.2,
    popularity: 85,
    priceInfo: "¥429",
  },
  {
    name: "对马岛之魂",
    nameEn: "Ghost of Tsushima",
    slug: slugify("Ghost of Tsushima"),
    description: "SIE出品的开放世界武士动作冒险游戏",
    platforms: ["console", "pc"],
    genres: ["rpg"],
    rating: 9.1,
    popularity: 82,
    priceInfo: "¥398",
  },
  {
    name: "战神：诸神黄昏",
    nameEn: "God of War Ragnarok",
    slug: slugify("God of War Ragnarok"),
    description: "圣莫妮卡出品的北欧神话动作冒险巨作",
    platforms: ["console", "pc"],
    genres: ["rpg"],
    rating: 9.4,
    popularity: 88,
    priceInfo: "¥398",
  },
  {
    name: "最终幻想16",
    nameEn: "Final Fantasy XVI",
    slug: slugify("Final Fantasy XVI"),
    description: "SE经典JRPG系列，全新动作战斗风格",
    platforms: ["console", "pc"],
    genres: ["rpg"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "¥398",
  },
  {
    name: "蔚蓝",
    nameEn: "Celeste",
    slug: slugify("Celeste"),
    description: "像素风高难度平台跳跃游戏，温暖的登山故事",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.3,
    popularity: 72,
    priceInfo: "¥70",
  },
  {
    name: "空洞骑士",
    nameEn: "Hollow Knight",
    slug: slugify("Hollow Knight"),
    description: "手绘风格银河恶魔城类游戏，庞大的地下王国",
    platforms: ["pc", "console"],
    genres: ["rpg", "puzzle"],
    rating: 9.4,
    popularity: 80,
    priceInfo: "¥48",
  },
  {
    name: "哈迪斯",
    nameEn: "Hades",
    slug: slugify("Hades"),
    description: "Supergiant出品的Roguelike动作游戏，希腊神话冥界逃脱",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.4,
    popularity: 85,
    priceInfo: "¥80",
  },
  {
    name: "星露谷物语",
    nameEn: "Stardew Valley",
    slug: slugify("Stardew Valley"),
    description: "像素风农场模拟经营游戏，治愈系种田生活",
    platforms: ["pc", "console", "mobile"],
    genres: ["simulation"],
    rating: 9.3,
    popularity: 85,
    priceInfo: "¥48",
  },
  {
    name: "超级马里奥兄弟 惊奇",
    nameEn: "Super Mario Bros. Wonder",
    slug: slugify("Super Mario Bros Wonder"),
    description: "任天堂经典2D平台游戏新作，创意惊奇花机制",
    platforms: ["console"],
    genres: ["puzzle"],
    rating: 9.0,
    popularity: 82,
    priceInfo: "¥429",
  },
  {
    name: "八方旅人2",
    nameEn: "Octopath Traveler II",
    slug: slugify("Octopath Traveler II"),
    description: "SE复古像素JRPG，八位旅人的交织命运",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.8,
    popularity: 72,
    priceInfo: "¥398",
  },

];
