import type { RawSeedGame } from "./types";
import { slugify } from "./types";

export const CROSS_PLATFORM_GAMES: RawSeedGame[] = [
  {
    name: "原神",
    nameEn: "Genshin Impact",
    slug: slugify("Genshin Impact"),
    description: "米哈游出品的开放世界冒险RPG，元素反应战斗系统",
    platforms: ["pc", "mobile", "console"],
    genres: ["rpg"],
    rating: 8.5,
    popularity: 95,
    priceInfo: "免费",
  },
  {
    name: "Apex英雄",
    nameEn: "Apex Legends",
    slug: slugify("Apex Legends"),
    description: "EA出品的英雄大逃杀射击游戏，快节奏战斗",
    platforms: ["pc", "console", "mobile"],
    genres: ["fps", "battle_royale"],
    rating: 8.5,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "堡垒之夜",
    nameEn: "Fortnite",
    slug: slugify("Fortnite"),
    description: "Epic出品的建造+大逃杀射击游戏，文化现象级",
    platforms: ["pc", "console", "mobile"],
    genres: ["fps", "battle_royale"],
    rating: 8.0,
    popularity: 92,
    priceInfo: "免费",
  },
  {
    name: "我的世界",
    nameEn: "Minecraft",
    slug: slugify("Minecraft"),
    description: "Mojang出品的沙盒创造游戏，无限自由建造",
    platforms: ["pc", "console", "mobile"],
    genres: ["simulation", "puzzle"],
    rating: 9.3,
    popularity: 98,
    priceInfo: "¥89",
  },
  {
    name: "火箭联盟",
    nameEn: "Rocket League",
    slug: slugify("Rocket League"),
    description: "汽车足球竞技游戏，简单规则深度玩法",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 8.8,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "糖豆人",
    nameEn: "Fall Guys",
    slug: slugify("Fall Guys"),
    description: "大型多人派对竞技游戏，可爱风闯关淘汰赛",
    platforms: ["pc", "console", "mobile"],
    genres: ["puzzle"],
    rating: 7.8,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "Among Us",
    nameEn: "Among Us",
    slug: slugify("Among Us"),
    description: "社交推理游戏，找出太空船上的冒充者",
    platforms: ["pc", "mobile", "console"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "泰拉瑞亚",
    nameEn: "Terraria",
    slug: slugify("Terraria"),
    description: "2D沙盒冒险游戏，挖掘、战斗与建造",
    platforms: ["pc", "console", "mobile"],
    genres: ["rpg", "simulation"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "¥36",
  },
  {
    name: "死亡细胞",
    nameEn: "Dead Cells",
    slug: slugify("Dead Cells"),
    description: "Roguelike银河城动作游戏，流畅战斗手感",
    platforms: ["pc", "console", "mobile"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥80",
  },
  {
    name: "饥荒联机版",
    nameEn: "Don't Starve Together",
    slug: slugify("Dont Starve Together"),
    description: "Klei出品的多人生存冒险游戏，蒂姆伯顿风格",
    platforms: ["pc", "console", "mobile"],
    genres: ["simulation", "strategy"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥24",
  },
  {
    name: "传说法师",
    nameEn: "Wizard of Legend",
    slug: slugify("Wizard of Legend"),
    description: "快节奏魔法Roguelike动作游戏",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.0,
    popularity: 60,
    priceInfo: "¥52",
  },
  {
    name: "双人成行",
    nameEn: "It Takes Two",
    slug: slugify("It Takes Two"),
    description: "Hazelight出品的双人合作冒险游戏，TGA年度最佳",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.5,
    popularity: 85,
    priceInfo: "¥198",
  },
  {
    name: "胡闹厨房2",
    nameEn: "Overcooked! 2",
    slug: slugify("Overcooked 2"),
    description: "混乱多人合作烹饪游戏，考验配合与手速",
    platforms: ["pc", "console"],
    genres: ["simulation", "puzzle"],
    rating: 8.8,
    popularity: 75,
    priceInfo: "¥100",
  },
  {
    name: "人类一败涂地",
    nameEn: "Human: Fall Flat",
    slug: slugify("Human Fall Flat"),
    description: "物理解谜冒险游戏，搞怪操作带来欢笑",
    platforms: ["pc", "console", "mobile"],
    genres: ["puzzle"],
    rating: 8.0,
    popularity: 75,
    priceInfo: "¥48",
  },
  {
    name: "无人深空",
    nameEn: "No Man's Sky",
    slug: slugify("No Mans Sky"),
    description: "Hello Games出品的太空探索生存游戏，程序生成宇宙",
    platforms: ["pc", "console"],
    genres: ["simulation", "rpg"],
    rating: 8.5,
    popularity: 75,
    priceInfo: "¥130",
  },
  {
    name: "英灵神殿",
    nameEn: "Valheim",
    slug: slugify("Valheim"),
    description: "北欧神话主题的多人生存建造游戏",
    platforms: ["pc"],
    genres: ["simulation", "rpg"],
    rating: 8.8,
    popularity: 78,
    priceInfo: "¥68",
  },
  {
    name: "恐鬼症",
    nameEn: "Phasmophobia",
    slug: slugify("Phasmophobia"),
    description: "四人合作恐怖调查游戏，调查超自然现象",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥46",
  },
  {
    name: "幻兽帕鲁",
    nameEn: "Palworld",
    slug: slugify("Palworld"),
    description: "怪物收集+生存建造游戏，帕鲁世界冒险",
    platforms: ["pc", "console"],
    genres: ["rpg", "simulation"],
    rating: 7.8,
    popularity: 88,
    priceInfo: "¥90",
  },
  {
    name: "三角战略",
    nameEn: "Triangle Strategy",
    slug: slugify("Triangle Strategy"),
    description: "SE出品的像素风战棋RPG，多路线分支剧情",
    platforms: ["pc", "console"],
    genres: ["strategy", "rpg"],
    rating: 8.5,
    popularity: 65,
    priceInfo: "¥398",
  },
  {
    name: "火焰纹章：风花雪月",
    nameEn: "Fire Emblem: Three Houses",
    slug: slugify("Fire Emblem Three Houses"),
    description: "任天堂经典战棋RPG，三学级剧情路线",
    platforms: ["console"],
    genres: ["strategy", "rpg"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥429",
  },
  {
    name: "勇者斗恶龙11",
    nameEn: "Dragon Quest XI",
    slug: slugify("Dragon Quest XI"),
    description: "SE经典日式RPG系列，传统JRPG的集大成之作",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 75,
    priceInfo: "¥298",
  },
  {
    name: "女神异闻录5 皇家版",
    nameEn: "Persona 5 Royal",
    slug: slugify("Persona 5 Royal"),
    description: "ATLUS经典JRPG，日常校园+异界战斗",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.5,
    popularity: 82,
    priceInfo: "¥398",
  },
  {
    name: "节奏光剑",
    nameEn: "Beat Saber",
    slug: slugify("Beat Saber"),
    description: "VR音乐节奏游戏，光剑切割音符，极致沉浸",
    platforms: ["pc"],
    genres: ["rhythm"],
    rating: 9.2,
    popularity: 78,
    priceInfo: "¥99",
  },
  {
    name: "太鼓达人",
    nameEn: "Taiko no Tatsujin",
    slug: slugify("Taiko no Tatsujin"),
    description: "万代经典太鼓音乐节奏游戏，咚咚咔咔！",
    platforms: ["console", "mobile"],
    genres: ["rhythm"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥300",
  },
  {
    name: "DEEMO",
    nameEn: "DEEMO",
    slug: slugify("DEEMO"),
    description: "雷亚出品的钢琴风音乐游戏，唯美故事",
    platforms: ["mobile", "console"],
    genres: ["rhythm"],
    rating: 9.0,
    popularity: 68,
    priceInfo: "¥12",
  },
  {
    name: "极品飞车：不羁",
    nameEn: "Need for Speed Unbound",
    slug: slugify("Need for Speed Unbound"),
    description: "EA旗舰赛车游戏，街头竞速文化",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 7.8,
    popularity: 72,
    priceInfo: "¥298",
  },
  {
    name: "GT赛车7",
    nameEn: "Gran Turismo 7",
    slug: slugify("Gran Turismo 7"),
    description: "索尼旗舰模拟赛车游戏，真实驾驶体验",
    platforms: ["console"],
    genres: ["racing"],
    rating: 8.8,
    popularity: 78,
    priceInfo: "¥498",
  },
  {
    name: "马里奥+疯狂兔子",
    nameEn: "Mario + Rabbids Sparks of Hope",
    slug: slugify("Mario Rabbids Sparks of Hope"),
    description: "育碧出品的马里奥回合策略游戏",
    platforms: ["console"],
    genres: ["strategy"],
    rating: 8.5,
    popularity: 68,
    priceInfo: "¥399",
  },
  {
    name: "潜水员戴夫",
    nameEn: "Dave the Diver",
    slug: slugify("Dave the Diver"),
    description: "深海探险+寿司店经营的混合独立游戏",
    platforms: ["pc", "console"],
    genres: ["simulation", "rpg"],
    rating: 9.0,
    popularity: 80,
    priceInfo: "¥138",
  },
  {
    name: "异度之刃3",
    nameEn: "Xenoblade Chronicles 3",
    slug: slugify("Xenoblade Chronicles 3"),
    description: "Monolith出品的史诗级JRPG，庞大世界观",
    platforms: ["console"],
    genres: ["rpg"],
    rating: 8.8,
    popularity: 72,
    priceInfo: "¥429",
  },
  {
    name: "生化危机4 重制版",
    nameEn: "Resident Evil 4 Remake",
    slug: slugify("Resident Evil 4 Remake"),
    description: "卡普空经典恐怖射击游戏重制版",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 9.2,
    popularity: 85,
    priceInfo: "¥325",
  },
  {
    name: "植物大战僵尸2",
    nameEn: "Plants vs. Zombies 2",
    slug: slugify("Plants vs Zombies 2"),
    description: "经典策略塔防游戏续作，植物守卫家园",
    platforms: ["mobile"],
    genres: ["strategy", "puzzle"],
    rating: 7.5,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "荒野乱斗",
    nameEn: "Brawl Stars",
    slug: slugify("Brawl Stars"),
    description: "Supercell出品的多人竞技手游，多种对战模式",
    platforms: ["mobile"],
    genres: ["fps", "moba"],
    rating: 8.2,
    popularity: 82,
    priceInfo: "免费",
  },
  {
    name: "文明变革2",
    nameEn: "Civilization Revolution 2",
    slug: slugify("Civilization Revolution 2"),
    description: "文明系列手机简化版，随时随地策略征服",
    platforms: ["mobile"],
    genres: ["strategy"],
    rating: 7.5,
    popularity: 55,
    priceInfo: "¥30",
  },
  {
    name: "纪念碑谷",
    nameEn: "Monument Valley",
    slug: slugify("Monument Valley"),
    description: "ustwo出品的视觉错觉解谜游戏，极简美学",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "¥25",
  },
  {
    name: "密室逃脱",
    nameEn: "The Room",
    slug: slugify("The Room"),
    description: "Fireproof出品的3D机关解谜游戏系列",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 9.0,
    popularity: 72,
    priceInfo: "¥6",
  },
  {
    name: "旷野之息",
    nameEn: "The Legend of Zelda: Breath of the Wild",
    slug: slugify("Zelda Breath of the Wild"),
    description: "任天堂重新定义开放世界的杰作，自由探索海拉鲁",
    platforms: ["console"],
    genres: ["rpg", "puzzle"],
    rating: 9.8,
    popularity: 95,
    priceInfo: "¥429",
  },
  {
    name: "喷射战士3",
    nameEn: "Splatoon 3",
    slug: slugify("Splatoon 3"),
    description: "任天堂出品的涂色射击对战游戏",
    platforms: ["console"],
    genres: ["fps"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "¥429",
  },
  {
    name: "斯普拉遁3",
    nameEn: "Pikmin 4",
    slug: slugify("Pikmin 4"),
    description: "任天堂出品的策略冒险游戏，指挥小精灵皮克敏",
    platforms: ["console"],
    genres: ["strategy", "puzzle"],
    rating: 8.8,
    popularity: 70,
    priceInfo: "¥429",
  },
  {
    name: "以撒的结合",
    nameEn: "The Binding of Isaac",
    slug: slugify("The Binding of Isaac"),
    description: "经典Roguelike地牢射击游戏，海量道具组合",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 75,
    priceInfo: "¥48",
  },
  {
    name: "深岩银河",
    nameEn: "Deep Rock Galactic",
    slug: slugify("Deep Rock Galactic"),
    description: "四人合作矿洞射击游戏，太空矮人挖矿打虫",
    platforms: ["pc", "console"],
    genres: ["fps"],
    rating: 9.0,
    popularity: 78,
    priceInfo: "¥68",
  },
  {
    name: "逃脱者2",
    nameEn: "The Escapists 2",
    slug: slugify("The Escapists 2"),
    description: "像素风越狱模拟游戏，策略规划逃脱方案",
    platforms: ["pc", "console", "mobile"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 65,
    priceInfo: "¥68",
  },
  {
    name: "模拟城市：建设",
    nameEn: "SimCity BuildIt",
    slug: slugify("SimCity BuildIt"),
    description: "EA经典城市建设模拟手游",
    platforms: ["mobile"],
    genres: ["simulation"],
    rating: 7.5,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "影之诗",
    nameEn: "Shadowverse",
    slug: slugify("Shadowverse"),
    description: "Cygames出品的日系动漫风卡牌对战游戏",
    platforms: ["pc", "mobile"],
    genres: ["card"],
    rating: 8.0,
    popularity: 65,
    priceInfo: "免费",
  },
  {
    name: "游戏王：大师决斗",
    nameEn: "Yu-Gi-Oh! Master Duel",
    slug: slugify("Yu-Gi-Oh Master Duel"),
    description: "KONAMI出品的游戏王数字卡牌对战游戏",
    platforms: ["pc", "console", "mobile"],
    genres: ["card", "strategy"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "漫威终极逆转",
    nameEn: "Marvel Snap",
    slug: slugify("Marvel Snap"),
    description: "漫威IP快节奏策略卡牌游戏，每局3分钟",
    platforms: ["pc", "mobile"],
    genres: ["card"],
    rating: 8.5,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "传送门2",
    nameEn: "Portal 2",
    slug: slugify("Portal 2"),
    description: "Valve出品的第一人称物理解谜游戏，神级关卡设计",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.6,
    popularity: 82,
    priceInfo: "¥36",
  },
  {
    name: "见证者",
    nameEn: "The Witness",
    slug: slugify("The Witness"),
    description: "Jonathan Blow出品的开放世界解谜游戏，线条谜题",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.0,
    popularity: 65,
    priceInfo: "¥138",
  },
  {
    name: "超级马里奥：奥德赛",
    nameEn: "Super Mario Odyssey",
    slug: slugify("Super Mario Odyssey"),
    description: "任天堂3D平台动作冒险游戏，帽子附身机制",
    platforms: ["console"],
    genres: ["puzzle"],
    rating: 9.5,
    popularity: 88,
    priceInfo: "¥429",
  },
  {
    name: "地铁：离去",
    nameEn: "Metro Exodus",
    slug: slugify("Metro Exodus"),
    description: "4A Games出品的末世FPS冒险游戏，俄罗斯废土",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥198",
  },
  {
    name: "流放之路",
    nameEn: "Path of Exile",
    slug: slugify("Path of Exile"),
    description: "GGG出品的免费ARPG，极致暗黑风格与Build深度",
    platforms: ["pc"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "赛博朋克2077",
    nameEn: "Cyberpunk 2077",
    slug: slugify("Cyberpunk 2077"),
    description: "CDPR出品的开放世界赛博朋克RPG",
    platforms: ["pc", "console"],
    genres: ["rpg", "fps"],
    rating: 8.5,
    popularity: 88,
    priceInfo: "¥298",
  },
  {
    name: "Baba Is You",
    nameEn: "Baba Is You",
    slug: slugify("Baba Is You"),
    description: "创新规则解谜游戏，推动文字改变游戏规则",
    platforms: ["pc", "console"],
    genres: ["puzzle"],
    rating: 9.3,
    popularity: 70,
    priceInfo: "¥48",
  },
  {
    name: "异星工厂2",
    nameEn: "Factorio 2",
    slug: slugify("Shapez"),
    description: "抽象工厂自动化游戏，设计和优化形状处理流水线",
    platforms: ["pc"],
    genres: ["puzzle", "simulation"],
    rating: 8.8,
    popularity: 65,
    priceInfo: "¥36",
  },
  {
    name: "激战2",
    nameEn: "Guild Wars 2",
    slug: slugify("Guild Wars 2"),
    description: "ArenaNet出品的MMORPG，动态事件与WvW",
    platforms: ["pc"],
    genres: ["rpg"],
    rating: 8.5,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "最终幻想14",
    nameEn: "Final Fantasy XIV",
    slug: slugify("Final Fantasy XIV"),
    description: "SE出品的MMORPG，顶级剧情与副本设计",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "月卡制",
  },
  {
    name: "Dota自走棋",
    nameEn: "Auto Chess",
    slug: slugify("Auto Chess"),
    description: "开创自走棋品类的策略对战游戏",
    platforms: ["pc", "mobile"],
    genres: ["strategy", "card"],
    rating: 7.8,
    popularity: 65,
    priceInfo: "免费",
  },
  {
    name: "光·遇",
    nameEn: "Sky: Children of the Light",
    slug: slugify("Sky Children of the Light"),
    description: "陈星汉出品的社交冒险游戏，唯美飞翔体验",
    platforms: ["mobile", "console"],
    genres: ["puzzle", "simulation"],
    rating: 8.8,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "决战！平安京",
    nameEn: "Onmyoji Arena",
    slug: slugify("Onmyoji Arena"),
    description: "网易出品的阴阳师IP MOBA手游",
    platforms: ["mobile"],
    genres: ["moba"],
    rating: 7.8,
    popularity: 65,
    priceInfo: "免费",
  },
  {
    name: "重返未来：1999",
    nameEn: "Reverse: 1999",
    slug: slugify("Reverse 1999"),
    description: "回合制卡牌RPG手游，复古奇幻世界观",
    platforms: ["mobile", "pc"],
    genres: ["rpg", "card"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "全境封锁2",
    nameEn: "Tom Clancy's The Division 2",
    slug: slugify("The Division 2"),
    description: "育碧出品的开放世界TPS刷装备射击游戏",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 8.0,
    popularity: 70,
    priceInfo: "¥198",
  },
  {
    name: "群星",
    nameEn: "Stellaris",
    slug: slugify("Stellaris"),
    description: "P社出品的太空大战略游戏，银河帝国经营",
    platforms: ["pc", "console"],
    genres: ["strategy", "simulation"],
    rating: 8.8,
    popularity: 72,
    priceInfo: "¥112",
  },

];
