import type { RawSeedGame } from "./types";
import { slugify } from "./types";

export const MOBILE_GAMES: RawSeedGame[] = [
  {
    name: "王者荣耀",
    nameEn: "Honor of Kings",
    slug: slugify("Honor of Kings"),
    description: "腾讯旗舰手游MOBA，国民级5v5对战游戏",
    platforms: ["mobile"],
    genres: ["moba"],
    rating: 8.5,
    popularity: 98,
    priceInfo: "免费",
  },
  {
    name: "和平精英",
    nameEn: "Game for Peace",
    slug: slugify("Game for Peace"),
    description: "腾讯出品的战术竞技手游，大逃杀玩法",
    platforms: ["mobile"],
    genres: ["fps", "battle_royale"],
    rating: 8.0,
    popularity: 92,
    priceInfo: "免费",
  },
  {
    name: "明日方舟",
    nameEn: "Arknights",
    slug: slugify("Arknights"),
    description: "鹰角出品的策略塔防手游，丰富的剧情与角色养成",
    platforms: ["mobile"],
    genres: ["strategy", "card"],
    rating: 8.8,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "蛋仔派对",
    nameEn: "Eggy Party",
    slug: slugify("Eggy Party"),
    description: "网易出品的派对竞技手游，多人闯关社交",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 7.5,
    popularity: 88,
    priceInfo: "免费",
  },
  {
    name: "节奏大师",
    nameEn: "Rhythm Master",
    slug: slugify("Rhythm Master"),
    description: "腾讯经典音乐节奏手游，多种曲目挑战",
    platforms: ["mobile"],
    genres: ["rhythm"],
    rating: 7.8,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "元梦之星",
    nameEn: "Dream Star",
    slug: slugify("Dream Star"),
    description: "腾讯出品的派对竞技游戏，创意闯关与社交",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 7.2,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "金铲铲之战",
    nameEn: "Teamfight Tactics Mobile",
    slug: slugify("Teamfight Tactics Mobile"),
    description: "拳头出品的自走棋手游，策略卡牌构筑对战",
    platforms: ["mobile"],
    genres: ["strategy", "card"],
    rating: 8.0,
    popularity: 82,
    priceInfo: "免费",
  },
  {
    name: "第五人格",
    nameEn: "Identity V",
    slug: slugify("Identity V"),
    description: "网易出品的非对称对抗手游，1v4追逃竞技",
    platforms: ["mobile"],
    genres: ["strategy", "puzzle"],
    rating: 8.0,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "崩坏：星穹铁道",
    nameEn: "Honkai: Star Rail",
    slug: slugify("Honkai Star Rail"),
    description: "米哈游出品的回合制RPG，星际冒险剧情",
    platforms: ["mobile", "pc"],
    genres: ["rpg", "strategy"],
    rating: 8.8,
    popularity: 90,
    priceInfo: "免费",
  },
  {
    name: "阴阳师",
    nameEn: "Onmyoji",
    slug: slugify("Onmyoji"),
    description: "网易出品的日式和风RPG手游，式神养成对战",
    platforms: ["mobile"],
    genres: ["rpg", "card"],
    rating: 8.2,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "Phigros",
    nameEn: "Phigros",
    slug: slugify("Phigros"),
    description: "国产创新音游，动态判定线设计，优秀曲库",
    platforms: ["mobile"],
    genres: ["rhythm"],
    rating: 9.0,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "Cytus II",
    nameEn: "Cytus II",
    slug: slugify("Cytus II"),
    description: "雷亚出品的科幻故事音乐游戏，沉浸式剧情音游",
    platforms: ["mobile"],
    genres: ["rhythm"],
    rating: 9.2,
    popularity: 68,
    priceInfo: "¥18",
  },
  {
    name: "部落冲突",
    nameEn: "Clash of Clans",
    slug: slugify("Clash of Clans"),
    description: "Supercell出品的策略塔防经营游戏，全球热门",
    platforms: ["mobile"],
    genres: ["strategy", "simulation"],
    rating: 8.3,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "皇室战争",
    nameEn: "Clash Royale",
    slug: slugify("Clash Royale"),
    description: "Supercell出品的即时策略卡牌对战游戏",
    platforms: ["mobile"],
    genres: ["card", "strategy"],
    rating: 8.2,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "使命召唤手游",
    nameEn: "Call of Duty Mobile",
    slug: slugify("Call of Duty Mobile"),
    description: "动视经典FPS系列手游版，多模式射击体验",
    platforms: ["mobile"],
    genres: ["fps"],
    rating: 8.0,
    popularity: 82,
    priceInfo: "免费",
  },
  {
    name: "暗区突围",
    nameEn: "Arena Breakout",
    slug: slugify("Arena Breakout"),
    description: "腾讯出品的硬核撤离射击手游，Tarkov式玩法",
    platforms: ["mobile"],
    genres: ["fps", "strategy"],
    rating: 8.3,
    popularity: 78,
    priceInfo: "免费",
  },
  {
    name: "三国志·战略版",
    nameEn: "Three Kingdoms Tactics",
    slug: slugify("Three Kingdoms Tactics"),
    description: "三国题材SLG手游，大地图策略征战",
    platforms: ["mobile"],
    genres: ["strategy"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "QQ飞车手游",
    nameEn: "QQ Speed Mobile",
    slug: slugify("QQ Speed Mobile"),
    description: "腾讯经典竞速手游，休闲竞速赛车",
    platforms: ["mobile"],
    genres: ["racing"],
    rating: 7.5,
    popularity: 72,
    priceInfo: "免费",
  },
  {
    name: "跑跑卡丁车手游",
    nameEn: "KartRider Rush+",
    slug: slugify("KartRider Rush Plus"),
    description: "经典卡丁车竞速手游，道具与竞速双模式",
    platforms: ["mobile"],
    genres: ["racing"],
    rating: 7.8,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "开心消消乐",
    nameEn: "Happy Match",
    slug: slugify("Happy Match"),
    description: "国民级三消益智游戏，休闲解谜",
    platforms: ["mobile"],
    genres: ["puzzle"],
    rating: 7.0,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "最强蜗牛",
    nameEn: "Super Snail",
    slug: slugify("Super Snail"),
    description: "放置RPG手游，搞怪风格蜗牛养成冒险",
    platforms: ["mobile"],
    genres: ["rpg", "simulation"],
    rating: 7.5,
    popularity: 68,
    priceInfo: "免费",
  },
  {
    name: "绝区零",
    nameEn: "Zenless Zone Zero",
    slug: slugify("Zenless Zone Zero"),
    description: "米哈游出品的都市动作RPG手游",
    platforms: ["mobile", "pc"],
    genres: ["rpg"],
    rating: 8.2,
    popularity: 82,
    priceInfo: "免费",
  },

];
