import type { RawSeedGame } from "./types";
import { slugify } from "./types";

export const PC_GAMES: RawSeedGame[] = [
  {
    name: "反恐精英2",
    nameEn: "Counter-Strike 2",
    slug: slugify("Counter-Strike 2"),
    description: "Valve出品的经典团队竞技射击游戏，CS系列最新作",
    platforms: ["pc"],
    genres: ["fps"],
    rating: 8.5,
    popularity: 95,
    priceInfo: "免费",
  },
  {
    name: "无畏契约",
    nameEn: "Valorant",
    slug: slugify("Valorant"),
    description: "拳头出品的5v5战术射击游戏，融合英雄技能与精准射击",
    platforms: ["pc"],
    genres: ["fps"],
    rating: 8.3,
    popularity: 90,
    priceInfo: "免费",
  },
  {
    name: "Dota 2",
    nameEn: "Dota 2",
    slug: slugify("Dota 2"),
    description: "Valve出品的经典MOBA游戏，高深度战术竞技",
    platforms: ["pc"],
    genres: ["moba", "strategy"],
    rating: 8.8,
    popularity: 85,
    priceInfo: "免费",
  },
  {
    name: "英雄联盟",
    nameEn: "League of Legends",
    slug: slugify("League of Legends"),
    description: "全球最受欢迎的MOBA游戏，拳头游戏旗舰之作",
    platforms: ["pc"],
    genres: ["moba"],
    rating: 8.5,
    popularity: 95,
    priceInfo: "免费",
  },
  {
    name: "守望先锋2",
    nameEn: "Overwatch 2",
    slug: slugify("Overwatch 2"),
    description: "暴雪出品的团队英雄射击游戏，强调团队配合",
    platforms: ["pc", "console"],
    genres: ["fps"],
    rating: 7.5,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "文明6",
    nameEn: "Civilization VI",
    slug: slugify("Civilization VI"),
    description: "经典回合制策略游戏，从远古文明走向太空时代",
    platforms: ["pc"],
    genres: ["strategy"],
    rating: 9.0,
    popularity: 80,
    priceInfo: "¥199",
  },
  {
    name: "城市：天际线",
    nameEn: "Cities: Skylines",
    slug: slugify("Cities Skylines"),
    description: "城市建设模拟游戏，规划和管理你的都市",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 8.8,
    popularity: 75,
    priceInfo: "¥128",
  },
  {
    name: "艾尔登法环",
    nameEn: "Elden Ring",
    slug: slugify("Elden Ring"),
    description: "FromSoftware与宫崎英高的开放世界动作RPG巨作",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.5,
    popularity: 90,
    priceInfo: "¥298",
  },
  {
    name: "巫师3：狂猎",
    nameEn: "The Witcher 3: Wild Hunt",
    slug: slugify("The Witcher 3 Wild Hunt"),
    description: "CDPR出品的史诗级开放世界RPG，猎魔人杰洛特的冒险",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.6,
    popularity: 90,
    priceInfo: "¥127",
  },
  {
    name: "博德之门3",
    nameEn: "Baldur's Gate 3",
    slug: slugify("Baldurs Gate 3"),
    description: "Larian出品的D&D规则CRPG，极致的角色扮演体验",
    platforms: ["pc", "console"],
    genres: ["rpg", "strategy"],
    rating: 9.7,
    popularity: 88,
    priceInfo: "¥298",
  },
  {
    name: "星际争霸2",
    nameEn: "StarCraft II",
    slug: slugify("StarCraft II"),
    description: "暴雪经典即时战略游戏，电竞RTS标杆",
    platforms: ["pc"],
    genres: ["strategy"],
    rating: 9.0,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "全面战争：三国",
    nameEn: "Total War: Three Kingdoms",
    slug: slugify("Total War Three Kingdoms"),
    description: "Creative Assembly出品的三国题材大战略游戏",
    platforms: ["pc"],
    genres: ["strategy"],
    rating: 8.5,
    popularity: 72,
    priceInfo: "¥268",
  },
  {
    name: "缺氧",
    nameEn: "Oxygen Not Included",
    slug: slugify("Oxygen Not Included"),
    description: "Klei出品的太空殖民模拟经营，管理复杂的生存系统",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.1,
    popularity: 70,
    priceInfo: "¥79",
  },
  {
    name: "环世界",
    nameEn: "RimWorld",
    slug: slugify("RimWorld"),
    description: "AI驱动的殖民地管理模拟，每局都是独特的故事",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.3,
    popularity: 78,
    priceInfo: "¥108",
  },
  {
    name: "永劫无间",
    nameEn: "Naraka: Bladepoint",
    slug: slugify("Naraka Bladepoint"),
    description: "东方武侠题材动作大逃杀，近战格斗为核心",
    platforms: ["pc"],
    genres: ["battle_royale"],
    rating: 7.8,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "彩虹六号：围攻",
    nameEn: "Rainbow Six Siege",
    slug: slugify("Rainbow Six Siege"),
    description: "育碧出品的战术团队射击游戏，主打环境破坏",
    platforms: ["pc", "console"],
    genres: ["fps", "strategy"],
    rating: 8.2,
    popularity: 78,
    priceInfo: "¥88",
  },
  {
    name: "绝地求生",
    nameEn: "PUBG: Battlegrounds",
    slug: slugify("PUBG Battlegrounds"),
    description: "开创大逃杀品类的里程碑射击游戏",
    platforms: ["pc"],
    genres: ["fps", "battle_royale"],
    rating: 7.5,
    popularity: 80,
    priceInfo: "免费",
  },
  {
    name: "命运2",
    nameEn: "Destiny 2",
    slug: slugify("Destiny 2"),
    description: "Bungie出品的科幻射击MMORPG，PvE与PvP结合",
    platforms: ["pc", "console"],
    genres: ["fps", "rpg"],
    rating: 8.0,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "暗黑破坏神4",
    nameEn: "Diablo IV",
    slug: slugify("Diablo IV"),
    description: "暴雪经典ARPG系列最新作，暗黑风格动作角色扮演",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.0,
    popularity: 82,
    priceInfo: "¥298",
  },
  {
    name: "炉石传说",
    nameEn: "Hearthstone",
    slug: slugify("Hearthstone"),
    description: "暴雪出品的数字卡牌对战游戏，简单上手深度策略",
    platforms: ["pc", "mobile"],
    genres: ["card", "strategy"],
    rating: 8.0,
    popularity: 75,
    priceInfo: "免费",
  },
  {
    name: "万智牌：竞技场",
    nameEn: "Magic: The Gathering Arena",
    slug: slugify("Magic The Gathering Arena"),
    description: "经典集换式卡牌游戏的数字版，极深策略卡牌",
    platforms: ["pc", "mobile"],
    genres: ["card", "strategy"],
    rating: 8.3,
    popularity: 70,
    priceInfo: "免费",
  },
  {
    name: "杀戮尖塔",
    nameEn: "Slay the Spire",
    slug: slugify("Slay the Spire"),
    description: "开创Roguelike卡牌构筑品类的独立游戏神作",
    platforms: ["pc", "mobile", "console"],
    genres: ["card", "strategy"],
    rating: 9.2,
    popularity: 82,
    priceInfo: "¥80",
  },
  {
    name: "极限竞速：地平线5",
    nameEn: "Forza Horizon 5",
    slug: slugify("Forza Horizon 5"),
    description: "微软旗舰开放世界赛车游戏，极致画面与驾驶体验",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 9.2,
    popularity: 85,
    priceInfo: "¥248",
  },
  {
    name: "尘埃拉力赛2.0",
    nameEn: "DiRT Rally 2.0",
    slug: slugify("DiRT Rally 2"),
    description: "硬核拉力赛车模拟游戏，真实越野驾驶体验",
    platforms: ["pc", "console"],
    genres: ["racing"],
    rating: 8.5,
    popularity: 60,
    priceInfo: "¥128",
  },
  {
    name: "戴森球计划",
    nameEn: "Dyson Sphere Program",
    slug: slugify("Dyson Sphere Program"),
    description: "国产太空工厂建设游戏，建造环绕恒星的戴森球",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.2,
    popularity: 78,
    priceInfo: "¥70",
  },
  {
    name: "工厂小镇",
    nameEn: "Factorio",
    slug: slugify("Factorio"),
    description: "极致的自动化工厂建设模拟游戏，强迫症的天堂",
    platforms: ["pc"],
    genres: ["simulation", "strategy"],
    rating: 9.5,
    popularity: 80,
    priceInfo: "¥160",
  },
  {
    name: "黑神话：悟空",
    nameEn: "Black Myth: Wukong",
    slug: slugify("Black Myth Wukong"),
    description: "国产3A动作RPG巨作，西游题材魂like战斗",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 9.0,
    popularity: 95,
    priceInfo: "¥268",
  },
  {
    name: "怪物猎人：荒野",
    nameEn: "Monster Hunter Wilds",
    slug: slugify("Monster Hunter Wilds"),
    description: "卡普空经典动作猎杀游戏系列，共斗巨型怪物",
    platforms: ["pc", "console"],
    genres: ["rpg"],
    rating: 8.8,
    popularity: 88,
    priceInfo: "¥396",
  },

];
